### PR TITLE
[Documentation] Fixed the syntax issue in Delete by Segment ID

### PR DESCRIPTION
**Pull request by siddhardhk**
In the Delete by Segment ID command the WHERE was misspelled as WERE

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
LGTM
@chenliang613 kindly review

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
