### PR TITLE
[ISSUE-4305] Optimize the constants and variable style

### PR DESCRIPTION
**Pull request by xubo245**
### Why is this PR needed?
 
 CONSTANTS should be like: UPPER_NAME;
variable should be lowerCamelCase

 ### What changes were proposed in this PR?

    CONSTANTS should be like: UPPER_NAME;
variable should be lowerCamelCase
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6380/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4672/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/764/

**Comment by chenliang613** [comment]
LGTM

**Pull request merged**
