### PR TITLE
[wip]revert logic of not deleting lock file, and delete lock file during unlock only if it had acquired lock before

### PR DESCRIPTION
**Pull request by akashrn5**
revert logic of not deleting lock file, and delete lock file during unlock only if it had acquired lock before
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by zzcclp** [comment]
@akashrn5 why revert this logic? and why just revert this logic for HDFS?

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4007/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4499/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3270/

**Comment by akashrn5** [comment]
@zzcclp we are testing the concurrent scenarios with this change, im still in testing phase of this PR if it can solve the concurent issues of lock in hdfs

**Comment by zzcclp** [comment]
ok, thanks for your reply, if it needs to revert this logic, we need to discuss whether remove the logic of deleting segment lock file auto.

**Pull request closed without merging**
