### PR TITLE
[HOTFIX] exclude servlet-api.jar and jsp-api.jar from dependency

### PR DESCRIPTION
**Pull request by zzcclp**
### Why is this PR needed?
When run app in idea, spark ui will throw exception.
 
 ### What changes were proposed in this PR?
servlet-api.jar 2.5 and jsp-api.jar 2.1 conflict with jetty, so exclude these two jars from dependencies.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/406/

**Comment by zzcclp** [comment]
@jackylk please review, thanks.

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2107/

**Comment by ajantha-bhat** [comment]
LGTM

**Pull request closed without merging**
