### PR TITLE
[CARBONDATA-2155][CARBONDATA-2152] [Presto] Fixed IS NULL not working correctly on string datatype with dictionary include in presto

### PR DESCRIPTION
**Pull request by anubhav100**
Fixed IS NULL not working correctly on string datatype with dictionary_include in presto integration
Fixed Min function working incorrectly for string type with dictionary include in presto integration

**Problem**: 
1.When Creating SliceArrayBlock In CarbonDictionaryDeocdeReadSupport We are not inserting null values In SliceArrayBlock,Carbon Internaly represents Null Value in Dictionary As @NU#LL$! So When Creating SliceArrayBlock using dictionary chunk if we are getting the first chunk it will always be MEMBER_DEFAULT_VAL which is represented as @NU#LL$!,then we should add null
as value in our slicearrayblock

2.**Bug releated to test cases** :Our carbondatastore creator was not filling our dict value with @NU#LL$! in the first position of dict file that  was causing test cases to fails after changes are done in carbondictionarydecodereadsupport 

**Solution**:
 1. When Creating SliceArrayBlock using dictionary chunk if we are getting the first chunk it will always be MEMBER_DEFAULT_VAL which is represented as @NU#LL$!,then we should add null

 2. **Testing-Only** : Refactored the CarbonDataStoreCreator Code to fill our dict value with @NU#LL$! in the  first position of dict file it was causing test cases to fail with the changes in code in this pr which should be there to make sure that test cases run smoothly

**Testing Results**:

**CARBONDATA-2152**

**presto:default> select min(l_shipmode) from lineitem;**
 **_col0 
**-------**
 **AIR**   
**(1 row)****

**Query 20180410_113517_00000_jpvh5, FINISHED, 1 node**
**Splits: 18 total, 18 done (100.00%)**
**0:02 [10K rows, 10KB] [4.26K rows/s, 4.24KB/s]**

**CARBONDATA-2155**

**presto:default> select l_shipmode from lineitem where l_shipmode is NULL;**
 ****l_shipmode** 
**------------**
 **NULL**       
**(1 row)****

**Query 20180410_113824_00002_jpvh5, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [10K rows, 10KB] [22.7K rows/s, 22.6KB/s]**

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 
 - [x] Any backward compatibility impacted?
 
 - [x] Document update required?

 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?yes new test 
        cases are added
        - How it is tested? Please attach test report.
          testing is done manually 
        - Is it a performance related change? Please attach the performance test report
           no.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3677/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4900/

**Comment by anubhav100** [comment]
retest his please

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4368/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3683/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4908/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3685/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4371/

**Comment by anubhav100** [comment]
@chenliang613 please review this pr

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4911/

**Comment by anubhav100** [comment]
retest this please

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4373/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3693/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4916/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4377/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4921/

**Comment by anubhav100** [comment]
@chenliang613 please review

**Comment by chenliang613** [comment]
verified, LGTM

**Pull request closed without merging**
