### PR TITLE
[CARBONDATA-1105] remove spark.version in submodule

### PR DESCRIPTION
**Pull request by cenyuhai**
support spark 2.1.1

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2354/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/233/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2357/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/236/

**Comment by QiangCai** [comment]
@cenyuhai 
please have a look PR1096.
https://github.com/apache/carbondata/pull/1096

We still need use spark2.10 as default.
and open to support spark2.1.x.

**Comment by chenliang613** [comment]
@cenyuhai  
1.Formally support spark 2.1.1 integration, need have a discussion and vote in dev mailing list.
2.For your PR, please first fix this issue:  currently in example/spark2/pom.xml, integration/spark2/pom.xml,  give the fixed spark version, this is issue, need remove it. spark version can be inherited from parent pom as per users' "mvn compile script"

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/256/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2836/

**Comment by QiangCai** [comment]
LGTM

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
