### PR TITLE
[CARBONDATA-1945] updated bad records handling for its default value

### PR DESCRIPTION
**Pull request by vandana7**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3028/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1797/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3028/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
