### PR TITLE
[CARBONDATA-4113] Partition prune and cache fix when carbon.read.partition.hive.direct is disabled.

### PR DESCRIPTION
**Pull request by ShreelekhyaG**
### Why is this PR needed?
 When `carbon.read.partition.hive.direct` is `false` then select queries on partition table result is invalid .
For a single partition, partition values are appended to form the wrong path when loaded by the same segment.
Ex: For partition on column `b`, path: `/tablepath/b=1/b=2`
 
 ### What changes were proposed in this PR?
In `PartitionCacheManager`,  changes made to handle single and multiple partitions. Encoded the URI path to handle space values in the string.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12444/job/ApacheCarbon_PR_Builder_2.4.5/3614/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12444/job/ApacheCarbonPRBuilder2.3/5374/

**Comment by kunal642** [comment]
retest this please

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12444/job/ApacheCarbon_PR_Builder_2.4.5/3642/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12444/job/ApacheCarbonPRBuilder2.3/5402/

**Comment by ShreelekhyaG** [comment]
retest this please

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12444/job/ApacheCarbonPRBuilder2.3/5407/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12444/job/ApacheCarbon_PR_Builder_2.4.5/3647/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
