### PR TITLE
[CARBONDATA-1187]Fixed linking and content issues

### PR DESCRIPTION
**Pull request by jatin9896**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/469/

**Comment by chenliang613** [comment]
LGTM

**Comment by chenliang613** [comment]
add to whielist

**Pull request closed without merging**
