### PR TITLE
[CARBONDATA-2911] Remove unused BTree related code

### PR DESCRIPTION
**Pull request by kevinjmh**
1. BTree related code is only used by a test class called`BTreeBlockFinderTest`.
2. BTreeDataRefNodeFinder in AbstractDetailQueryResultIterator never run. All dataRefNode are actually  instanceof BlockletDataRefNode

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/8276/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/205/

**Comment by jackylk** [comment]
LGTM

**Comment by xuchuanyin** [comment]
@jackylk I have doubt about the below scenario:
For sort_columns, the minmax is ordered for all the blocks/blocklets in one segment.

Suppose that we are doing filtering on sort_columns and the filter looks like Col1='bb'.
If the minmax values for blocklet#1, blocklet#2, blocklet#3 is [a,c), [c,d), [d,e).
After carbondata find max value of blocklet#1 already covers filter value 'bb', Will it **still compare** filter value 'bb' with the minmax of the rest blocklets#2/#3?

I though the BTree can be used to avoid these comparison. Am I wrong?

**Pull request closed without merging**
