### PR TITLE
[CARBONDATA-1269] Fixed bug for select operation in non existing database

### PR DESCRIPTION
**Pull request by geetikagupta16**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2930/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/344/

**Comment by jackylk** [comment]
LGTM

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
