### PR TITLE
[CARBONDATA-772]  NumberFormatException displays to user in spark 2.1

### PR DESCRIPTION
**Pull request by rahulforallp**
There were a problem with conversion of value from string to actual data-type for filter query.
So it needed to be parsed as parseInt and other.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1213/

**Comment by kumarvishal09** [comment]
Please provide detail description about this change

**Comment by rahulforallp** [comment]
@kumarvishal09 description added

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1217/

**Comment by chenliang613** [comment]
@rahulforallp please change tile to : [CARBONDATA-772] xxx

**Comment by rahulforallp** [comment]
@chenliang613 title edited

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1974/

**Comment by CarbonDataQA** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/60/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/90/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/628/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1259/

**Pull request closed without merging**
