### PR TITLE
[RELEASE] Updated new version number 1.3.0-SNAPSHOT in master branch pom files

### PR DESCRIPTION
**Pull request by ravipesala**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/194/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/318/

**Comment by chenliang613** [comment]
LGTM

**Comment by lionelcao** [comment]
LGTM

**Pull request merged**
