### PR TITLE
[CARBONDATA-1102] resolved int,short type bug for hive ,modified the hive example

### PR DESCRIPTION
**Pull request by anubhav100**
-resolve wrong data type casting in carbonhiverecordreader
-resolve wrong data type casting in intermediate file manager
-modify the hive example to remove non wanted add jar clause
-run manuaaly using hive example

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2120/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2121/

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
add to whitelist

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by anubhav100** [comment]
Why it's failed work fine on my machine

**Comment by chenliang613** [comment]
apache jenkins CI are not stable, let me check it at my local machine also.

**Comment by anubhav100** [comment]
@chenliang613 both build are successfull now can you merge it

**Comment by ravipesala** [comment]
LGTM, @chenliang613 please merge it.

**Pull request closed without merging**
