### PR TITLE
[CARBONDATA-1064] Make column group feature deprecated

### PR DESCRIPTION
**Pull request by jackylk**
After discussion in community (http://apache-carbondata-dev-mailing-list-archive.1130556.n5.nabble.com/About-ColumnGroup-feature-td14436.html), we conclude that column group feature will be deprecated. 

In this PR, column group feature is removed by throwing exception in parser

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2425/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/304/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/304/org.apache.carbondata$carbondata-spark/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/304/org.apache.carbondata$carbondata-spark/testReport/org.apache.carbondata.spark.util/AutoHighCardinalityIdentifyTestCase/skip_auto_identify_high_cardinality_column_for_column_group/'><strong>org.apache.carbondata.spark.util.AutoHighCardinalityIdentifyTestCase.skip auto identify high cardinality column for column group</strong></a></li></ul>

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2431/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/310/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
