### PR TITLE
[CARBONDATA-3311] support presto 0.217

### PR DESCRIPTION
**Pull request by ajantha-bhat**
[CARBONDATA-3311] support presto 0.217
supporting the latest version of the presto. please refer the release doc of presto for more details,
there is a change in presto-hive interfaces and hive analyser is added. 

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed? NA
 
 - [ ] Any backward compatibility impacted? NA
 
 - [ ] Document update required? NA

 - [ ] Testing done
UT passed.       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. NA

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
@ravipesala : please check

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2669/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10928/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2898/

**Comment by zzcclp** [comment]
I will check this pr in our QA env. If there is any issue, will let you know.

**Comment by zzcclp** [comment]
@ajantha-bhat @ravipesala I have tested presto 0.217 with this pr, it works well.

BTW, do we support multiple version for presto, for example: 0.216 and 0.217? 
I just removed all code about 'HiveAnalyzeProperties' (this class was added for presto 0.217), it works well with this pr and presto 0.216.

**Comment by chenliang613** [comment]
Verified, LGTM

**Comment by kunal642** [comment]
@ajantha-bhat supporting a new version should not be hotfix..Please create a JIRA for easy tracking

**Comment by ajantha-bhat** [comment]
@zzcclp : multiple versions may be hard to maintain. say If need 0.210, they can use with previous version of carbon.

@kunal642 : ok I created CARBONDATA-3311 now.

**Comment by zzcclp** [comment]
@ajantha-bhat @chenliang613 Thanks. Yeap,  it's  hard to maintain multiple versions of presto, presto has new released version every month.

**Comment by zzcclp** [comment]
LGTM, any suggestion for this pr? If no, I will merge this pr. @chenliang613 @ravipesala @kunal642

**Comment by kunal642** [comment]
LGTM

**Comment by zzcclp** [comment]
merged. Thanks @ajantha-bhat .

**Pull request closed without merging**
