### PR TITLE
[CARBONDATA-3107] Optimize error/exception coding for better debugging

### PR DESCRIPTION
**Pull request by kevinjmh**
Some error log in carbon is only a single line of conclusion message(like "Dataload failed"), and when we look into codes may found that is newly created exception without original exception, so more jobs need to be done to find the root cause.

To better locate the root cause when carbon fails, this PR propose to keep the original throwable for logging when wrapping it to another exception, and also log stack trace alone with error message.

Changes in this PR follows these rules:  (`e` is an exception)
                    
| Code Sample        | Problem   |  Suggest Modification  |
| --------   | -----:  | :----:  |
| `LOGGER.error(e);`     | no stack trace(e is taken as message instead of throwable) |   `LOGGER.error(e.getMessage(), e);`     |
| `LOGGER.error(e.getMessage());`     | no stack trace |   `LOGGER.error(e.getMessage(), e);`     |
| `catch ... throw new Exception("Error occur")`        |    useless message, no stack trace    |  `throw new Exception(e)`  |
| `catch ... throw new Exception(e.getMessage())`        |    no stack trace    |  `throw new Exception(e)`  |
| `catch ... throw new Exception(e.getMessage(), e)`        |   no need to call `getMessage()`   |   `throw new Exception(e)`   |
| `catch ... throw new Exception("Error occur: " + e.getMessage(), e)`        |    useless message    |  `throw new Exception(e)`  |
| `catch ... throw new Exception("DataLoad fail: " + e.getMessage())`        |    no stack trace    |  `throw new Exception("DataLoad fail: " + e.getMessage(), e)`  |

Some exceptions, such as MalformedCarbonCommandException, InterruptException, NumberFormatException, InvalidLoadOptionException and NoRetryException, do not have Constructor using `Throwable`, so this PR does not change it.

Currently split to multiple commits for better review.

---

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9402/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1144/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1350/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1356/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9409/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1660/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9708/

**Comment by xuchuanyin** [comment]
LGTM
Please fix the conflicts

**Comment by kevinjmh** [comment]
conflicts fixed.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1898/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10153/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2108/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2158/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1981/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10233/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2487/

**Comment by zzcclp** [comment]
Nice work.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2715/

**Comment by xuchuanyin** [comment]
retest this please

**Comment by xuchuanyin** [comment]
LGTM, waiting for the CI

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2591/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10851/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2822/

**Pull request closed without merging**
