### PR TITLE
[CARBONDATA-3713] update SDK doc about sort columns

### PR DESCRIPTION
**Pull request by ajantha-bhat**
### Why is this PR needed?
 sort columns API information is wrong in SDK and CSDK
 
 ### What changes were proposed in this PR?
update the correct information 
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1266/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2984/

**Comment by QiangCai** [comment]
LGTM

**Comment by akashrn5** [comment]
LGTM

**Pull request closed without merging**
