### PR TITLE
[CARBONDATA-1422] Fixed compaction issue when decimal is present

### PR DESCRIPTION
**Pull request by ravipesala**

### CODE REVIEW

**Comment by xuchuanyin** [comment]
It seems that `decimal` related modification is not shown in the changes. Do you mean `date`?

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/331/

**Comment by jackylk** [comment]
There is a table with decimal type in test("Compaction_Bug_JIRA_1422"), I think this PR is for that

**Comment by ravipesala** [comment]
@xuchuanyin As @jackylk told it is related to datatype conversion in carbon, if the request is from spark then we should do datatype conversion as per spark so that we should use `SparkDataTypeConverterImpl`

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
