### PR TITLE
[CARBONDATA-1547] Table should be dropped after running test

### PR DESCRIPTION
**Pull request by xubo245**
Table should be dropped after running test

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/271/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/393/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1024/

**Comment by xubo245** [comment]
please review it @QiangCai @jackylk

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
