### PR TITLE
[DOC] Improve java doc for DataSkewRangePartitioner

### PR DESCRIPTION
**Pull request by QiangCai**
- [x] Any interfaces changed?
 no
 - [x] Any backward compatibility impacted?
 no
 - [x] Document update required?
 no
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
          NA, only java doc change
        - How it is tested? Please attach test report.
          NA
        - Is it a performance related change? Please attach the performance test report.
          NA
        - Any additional information to help reviewers in testing this change.
          NA
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2855/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11115/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3086/

**Comment by sraghunandan** [comment]
LGTM

**Comment by manishnalla1994** [comment]
LGTM

**Pull request closed without merging**
