### PR TITLE
[CARBONDATA-1533] Fixed decimal data load fail issue and restricted max characters per column

### PR DESCRIPTION
**Pull request by manishgupta88**
1. Fixed data load failure when both precision and data falls in integer range for decimal data type
Analysis: When precision is <=9 for decimal data type then  by default integer type is selected for storing decimal data. Data is further compressed by checking min and max value range of data. If data is such that it falls in the Integer range only then exception is thrown during data load as encode method is not handling integer data type data during data load.

2. Restricted max characters per column to 32000 as we use short to store the length of each column
Analysis: Short data type is used to store length of each column in unsafe carbon row while writing data to off heap. If length is more than Short value then values goes into negative and while reading the same data negative array size exception is thrown.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/322/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/198/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/950/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/361/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/237/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/989/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
