### PR TITLE
[CARBONDATA-4345] update/delete operations failed when other format segments deleted from carbon table

### PR DESCRIPTION
**Pull request by maheshrajus**
### Why is this PR needed?
Update/delete operations failed when other format segments deleted from carbon table
Steps to reproduce:
1) create carbon table and load the data
2) create parquet/orc tables and load the data
3) add parquet/orc format segments in carbon table by alter add segment command
4) perform update/delete operations in carbon table and they will fail as table contains mixed format segments. This is expected behaviour only.
4) delete the other format segments which is added in step3
5) try to perform update/delete operation in carbon data. They should not fail
 
For update/delete operations we are checking if other format segments present in table path. If found then carbon data throwing exception by saying mixed format segments exists even though the other format segments deleted from table.
 ### What changes were proposed in this PR?
When we are checking other format segment present in carbon table then it should check only for SUCCESS/PARTIAL_SUCCESS segments. 
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/765/

**Comment by Indhumathi27** [comment]
@maheshrajus please rebase

**Comment by maheshrajus** [comment]
rebase is done

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6380/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/766/

**Comment by Indhumathi27** [comment]
LGTM

**Comment by Indhumathi27** [comment]
retest this please

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4639/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6384/

**Comment by maheshrajus** [comment]
restest this please

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4640/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6385/

**Pull request closed without merging**
