### PR TITLE
[CARBONDATA-1070]Not In Filter Expression Null Value Handling

### PR DESCRIPTION
**Pull request by sounakr**
Problem : Filter Test Case failure. 
a) Nullpointer Handling in Not Expression.
b) LessThan Filter Expression : Wrong calculation of StartKey for setting the Bits.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2101/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2103/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2104/

**Comment by gvramana** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2105/

**Pull request merged**
