### PR TITLE
[Documentation] Editorial Review

### PR DESCRIPTION
**Pull request by sgururajshetty**
Spelling correction fixed 
STATMENT to STATEMENT
granualrity to granularity

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3204/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4436/

**Comment by kunal642** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3960/

**Comment by jackylk** [comment]
LGTM

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
