### PR TITLE
[CARBONDATA-2053] added events for streaming

### PR DESCRIPTION
**Pull request by rahulforallp**
**This PR contains the code to fire events during following two steps :** 
1. before starting the stream and after the completion of stream
2. before adding a batch and after batch is added during stream.

  
 - [X] Any interfaces changed? No
 
 - [X] Any backward compatibility impacted? No
 
 - [X] Document update required? No

 - [X] Testing done
       Not Required because this PR donot contains any functional change. Only all the existing test case pass on CI is enough.
       
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2949/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2968/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1733/

**Comment by QiangCai** [comment]
LGTM

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
