### PR TITLE
[ISSUE-4342] Fix test case errors

### PR DESCRIPTION
**Pull request by QiangCai**
### Why is this PR needed?
 There are test case errors
 
 ### What changes were proposed in this PR?
1. update index schema of index cache
2. change mv name in testcase to avoid name confliction
    
 ### Does this PR introduce any user interface change?
 - No 

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by QiangCai** [comment]
image

**Comment by xubo245** [comment]
LGTM

**Comment by chenliang613** [comment]
@QiangCai  thanks for your fixs

**Comment by chenliang613** [comment]
LGTM

**Pull request merged**
