### PR TITLE
[Documentation] Updated Readme for Datamap Feature

### PR DESCRIPTION
**Pull request by sgururajshetty**
Readme is updated with the links to the following new topics on Datamap
> CarbonData Pre-aggregate DataMap
> CarbonData Timeseries DataMap

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2884/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4129/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3789/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
