### PR TITLE
[ISSUE-4351] Add github action for building

### PR DESCRIPTION
**Pull request by kevinjmh**
### Why is this PR needed?
build the project automatically  #4351 
 
 ### What changes were proposed in this PR?
 Add github action for building the project.
 Revert unfinished WIP commits about geo module to make sure building is success.
 
see:
https://github.com/apache/carbondata/actions/runs/11090247913

image
image

 ### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by chenliang613** [comment]
Thanks for contribute this pull request.  looks good to me

**Comment by chenliang613** [comment]
please other committer review it

**Comment by xubo245** [comment]
LGTM

**Comment by kevinjmh** [comment]
add: Cache thrift binary to skip the building work. See difference between attempt1 and attempt2:

[Attempt 1](https://github.com/apache/carbondata/actions/runs/11098627943/attempts/1)
image

[Attempt 2](https://github.com/apache/carbondata/actions/runs/11098627943/attempts/2)
image

**Comment by chenliang613** [comment]
LGTM

**Pull request merged**
