### PR TITLE
[CARBONDATA-172]Pushdown filters and broadcast equjoin to carbon and count star

### PR DESCRIPTION
**Pull request by ashokblend**
1.Pushdown spark unknown expression
2.Pushdown spark known expression
3.Pushdown spark equijoin
4. count star query

### CODE REVIEW

**Comment by ravipesala** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/

**Comment by chenliang613** [comment]
@ashokblend  please rebase this PR

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1221/

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1273/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/642/

**Comment by ashokblend** [comment]
closing it.

**Pull request closed without merging**
