### PR TITLE
[CARBONDATA-2669] Local Dictionary Store Size optimisation and other function issues

### PR DESCRIPTION
**Pull request by kumarvishal09**
### Problems
1. Local dictionary store size issue.
When all column data is empty and columns are not present in sort columns local dictionary size was more than no dictionary dictionary store size.
2. Page level dictionary merging Issue
While merging the page used dictionary values in a blocklet it was missing some of the dictionary values, this is because, AND operation was done on bitset
3. Local Dictionary null values
Null value was not added in LV because of this new dictionary values was getting generated for null values
4. Local dictionary generator thread specific

### **Solution:**
1. Added rle for unsorted dictionary values to reduce the size.
2. Now OR operation is performed while merging the dictionary values
3. Added LV for null values
4. Local dictionary generator task specific

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6629/

**Comment by akashrn5** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6630/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5458/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5505/

**Comment by kumarvishal09** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6631/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5459/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
