### PR TITLE
Change pom version to 1.3.0 for new release development

### PR DESCRIPTION
**Pull request by chenliang613**

### CODE REVIEW

**Comment by chenliang613** [comment]
duplicated pull request, close it.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/208/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/332/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/960/

**Pull request closed without merging**
