### PR TITLE
[HOTFIX] Fix wrong min/max index of measure

### PR DESCRIPTION
**Pull request by QiangCai**
[Background]
in sometimes, the measure's min/max value is wrong when there are more one pages.
[Root cause]
for example: ''' long compare = firstBuffer.getLong() - secondBuffer.getLong();'''
When the value overflow happened, it will give a wrong result.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/528/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/531/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/531/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
