### PR TITLE
[CARBONDATA-933] added compare test for orc vs carbondata benchmarking on hive

### PR DESCRIPTION
**Pull request by anubhav100**
this pr is used to do benchmarking of carbondata on hive vs orc on hive using compare test

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1840/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1841/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1851/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
