### PR TITLE
[HOTFIX] optimize the presto module name

### PR DESCRIPTION
**Pull request by lamber-ken**
This pr aims to optimize the presto module name.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed? NO
 
 - [x] Any backward compatibility impacted? NO
  
 - [x] Document update required? NO

 - [x] Testing done YES
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. OK

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3471/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3674/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11738/

**Comment by ajantha-bhat** [comment]
@lamber-ken : LGTM.

But if any other PR is open from you. suggest to add this change in that PR. 
For one letter change (which has no function impact) may be no need separate PR.

**Comment by lamber-ken** [comment]
> @lamber-ken : LGTM.
> 
> But if any other PR is open from you. suggest to add this change in that PR.
> For one letter change (which has no function impact) may be no need separate PR.

Thanks for your comment @ajantha-bhat, ok, I see. that's why I use `[HOTFIX]` as the title.

**Comment by brijoobopanna** [comment]
@lamber-ken :HOTFIX can be used for CI failure and other urgent blocking issues

**Comment by lamber-ken** [comment]
@brijoobopanna，thanks，btw，what's the right way to fix the minor bug. May be it is not suitable to add it to another PR. Because it may be not suitable to another PR's purpose

**Comment by brijoobopanna** [comment]
Thanks, @lamber-ken better to include with your other PR

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/20/

**Pull request closed without merging**
