### PR TITLE
[CARBONDATA-1819]Remove profiles for Spark-2.1 and Spark-2.2 in module assembly and spark-common-test

### PR DESCRIPTION
**Pull request by zzcclp**
Remove profiles for Spark-2.1 and Spark-2.2 in module assembly and spark-common-test

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1525/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1925/

**Comment by chenliang613** [comment]
LGTM, by default add spark2 module as dependency, don't need to use profile.

please @ravipesala  check it also.

**Comment by zzcclp** [comment]
@ravipesala please re-check this , thanks.

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
