### PR TITLE
[CARBONDATA-1482] fixed the failing test cases of presto integration

### PR DESCRIPTION
**Pull request by anubhav100**
1.builds are passing
2.added dependency for spark guava
3.throw exception in case carbondatastore creator is unable to load the data
4.fixed the timestamp issue due to which test cases are failing

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/168/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/44/

**Comment by anubhav100** [comment]
@chenliang613

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/798/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
