### PR TITLE
[CARBONDATA-2789] Support Hadoop 2.8.3 eco-system integration

### PR DESCRIPTION
**Pull request by chenliang613**
Add hadoop 2.8.3 profile and passed the compile

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7544/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/6298/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/6022/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
