### PR TITLE
[WIP][CARBONDATA-1551] Add test cases for the error when table that has Array<STRING> compact

### PR DESCRIPTION
**Pull request by xubo245**
When compact table that has array<string> complex data type, there also is an error:

The error message is shown in Description and comment of https://issues.apache.org/jira/browse/CARBONDATA-1551?filter=-2

The PR only add test case for this error, and no solution for it at present.

Analysis:
When compaction, the array<string> is expressed with one column, but normal should be two column, so it will out of index.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/727/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1364/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/729/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1366/

**Pull request closed without merging**
