### PR TITLE
[WIP] test_spark2.1.1

### PR DESCRIPTION
**Pull request by QiangCai**
Remove spark.version from spark2 module.
So the user can customize the spark2.x version

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2710/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/135/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/634/

**Comment by QiangCai** [comment]
the test of spark 2.1.1 passed

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2711/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/136/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/635/

**Comment by QiangCai** [comment]
the test of saprk 2.1.0 passed

**Comment by cenyuhai** [comment]
Now, I use this command to compile carboncata "mvn clean package -DskipTests -Phadoop-2.7.2 -Pspark-2.1 -Dspark.version=2.1.1".  it is ok. Why we should alter pom.xml?

**Comment by QiangCai** [comment]
in spark2 module, spark.verison will always be 2.1.0.

**Comment by chenliang613** [comment]
@QiangCai  this PR is duplicated with pr 1017, please close it.

**Pull request closed without merging**
