### PR TITLE
 [CARBONDATA-3597] Missed commit from PR-3483 (SCD2)

### PR DESCRIPTION
**Pull request by ravipesala**
There is a commit missed during PR merge of https://github.com/apache/carbondata/pull/3483 

### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/996/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2708/

**Comment by ajantha-bhat** [comment]
@jackylk : please check and merge.

**Comment by ajantha-bhat** [comment]
LGTM.

It was already reviewed in #3704 and changes are done as per latest insert flow now.

Instead of direct call to writer, it is better to use insert flow to write data.

so merging it.

**Pull request closed without merging**
