### PR TITLE
[CARBONDATA-3548]GeoHash column should not be allowed to be configured in column meta cache property

### PR DESCRIPTION
**Pull request by VenuReddy2103**
### Why is this PR needed?
 GeoHash column should not be allowed to be configured in column meta cache property.
This PR depends on #3436 . First commit is the original PR 3436 PR commit. Only second commit is the fix for this PR. Need to review only second commit.

 ### What changes were proposed in this PR?
During create table and alter table, validate column meta cache property for only schema columns instead of all the columns.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/1392/

**Comment by CarbonDataQA1** [comment]
Build Failed with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/1402/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1414/

**Comment by ydvpankaj97** [comment]
retest this please

**Comment by ydvpankaj97** [comment]
retest this please

**Comment by brijoobopanna** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1488/

**Comment by ajantha-bhat** [comment]
please rebase

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/8/

**Comment by VenuReddy2103** [comment]
This PR fix is already present in its base PR #3436 .
Can close this PR as not required anymore.

**Pull request closed without merging**
