### PR TITLE
[CARBONDATA-3226] Remove duplicated and useless files

### PR DESCRIPTION
**Pull request by runzhliu**
After a more careful inspection, remove some empty files. We can do it simply by a command as follows.

```bash
find . -empty | grep -e '\.scala' -e '\.java'
```

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 
 - [x] Any backward compatibility impacted?
 
 - [x] Document update required?

 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2283/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10542/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2503/

**Comment by xuchuanyin** [comment]
As far as I know, 'CarbonGetTableDetailComandTestCase.scala' is needed by some services, so better to ignore them. Additionally, we can add a comment in this file to remind other guys.

Actually I also found this about half a year ago and other guys told me about this.

**Comment by xubo245** [comment]
retest this please

**Comment by xubo245** [comment]
LGTM, thanks for your contribution!

**Comment by zzcclp** [comment]
LGTM

**Pull request closed without merging**
