### PR TITLE
[CARBONDATA-2128] Documentation for table path while creating the table

### PR DESCRIPTION
**Pull request by sgururajshetty**
Documentation for table path while creating the table

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
