### PR TITLE
[CARBONDATA-1219] Remove high.cardinality.row.count.percentage

### PR DESCRIPTION
**Pull request by srigopalmohanty**
The parameter high.cardinality.row.count.percentage should be removed and all the reference also needs to be removed from the configuration parameters document.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
LGTM
@chenliang613 kindly review

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/339/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2925/

**Comment by jackylk** [comment]
Is this PR intend to remove high.cardinality.row.count.percentage in `CarbonCommonConstraint` also?

**Comment by sgururajshetty** [comment]
@jackylk this PR is only for the document update as this feature is removed.

**Comment by chenliang613** [comment]
please solve the conflict.

**Pull request closed without merging**
