### PR TITLE
[CARBONDATA-1809]Add create table event

### PR DESCRIPTION
**Pull request by akashrn5**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [*] Any interfaces changed?
 NA
 - [*] Any backward compatibility impacted?
 NA
 - [*] Document update required?
NA
 - [*] Testing done
        UT not required, firing events will test this
       
 - [*] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1446/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1866/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1447/

**Comment by akashrn5** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1452/

**Pull request closed without merging**
