### PR TITLE
[CARBONDATA-1431] Fixed the parser for including time stamp and date field in dictionary include

### PR DESCRIPTION
**Pull request by PallaviSingh1992**
The dictionary_include should not contain date and timestamp fields, in this PR, I have fixed that issue and handled the same in the Parser so that, at the time of create query the user is given an exception for the same.

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/495/

**Comment by PallaviSingh1992** [comment]
retest this please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/496/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/498/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/499/

**Comment by PallaviSingh1992** [comment]
This check is not required

**Pull request closed without merging**
