### PR TITLE
[CARBONDATA-1680] Fixed Bug to show partition Ids for Hash Partition

### PR DESCRIPTION
**Pull request by SangeetaGulia**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed? No
 
 - [x] Any backward compatibility impacted? No
 
 - [x] Document update required? No

 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. (N/A)

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/729/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1957/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1958/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/730/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2276/

**Comment by lionelcao** [comment]
Hi, For hash partition we only need to show number of partitions. Why need to show the ids?

**Comment by SangeetaGulia** [comment]
I have displayed the partition_ids due to the bug raised in this jira https://issues.apache.org/jira/browse/CARBONDATA-1680

which says "Show Partition for Hash Partition doesn't display the partition id"

**Comment by lionelcao** [comment]
Hi @SangeetaGulia ,
look into the first image in the jira, under the highlighted text, we said the alter partition operation is not supported for hash partition table. So we don't show the ids. I suggest to keep the origin design.
Thanks for your contribution although : )

**Comment by SangeetaGulia** [comment]
Hi @lionelcao ,
Is there any plan to support alter partition operation for hash partition table in future?

**Comment by sraghunandan** [comment]
@SangeetaGulia partition requirement is being rewritten to solve additional usecases.Pls refer CARBONDATA-1850. Please verify whether you fix would be required or not

**Comment by SangeetaGulia** [comment]
@sraghunandan I have found two related tasks:
1) Create a system-level switch for supporting standard partition or carbon custom partition.
2) Support drop partition in carbon

So are we continuing support of custom partitions? and if yes then are we going to provide the support of drop partition for hash partition table?





Support drop partition in carbon
--




Support drop partition in carbon
--




Support drop partition in carbon
--




Support drop partition in carbon
--


Support drop partition in carbon
--

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/944/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2173/

**Pull request closed without merging**
