### PR TITLE
[CARBONDATA-2433] [Lucene GC Issue] Executor OOM because of GC when blocklet pruning is done using Lucene datamap

### PR DESCRIPTION
**Pull request by manishgupta88**
**Problem**
Executor OOM because of GC when blocklet pruning is done using Lucene datamap

**Analysis**
While seraching using lucene it creates a PriorityQueue to hold the documents. As size is not specified by default the PriorityQueue size is
equal to the number of lucene documents. As the docuemnts start getting added to the heap the GC time increases and after some time task fails due
to excessive GC and executor OOM occurs.
Reference blog: http://lucene.472066.n3.nabble.com/Optimization-of-memory-usage-in-PriorityQueue-td590355.html

**Fix**
Specify the limit for first search and after that use the searchAfter API to search in incremental order with gieven PriorityQueue size.

 - [ ] Any interfaces changed?
 No
 - [ ] Any backward compatibility impacted?
 No
 - [ ] Document update required?
No
 - [ ] Testing done
Manually verified with 3.7 billion data. For a query, GC time came down to 5 sec from 40 min.
  
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4461/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5621/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4714/

**Comment by jackylk** [comment]
Hi, I tried this PR in a table with 60M row table, and I added log in the loop you add, it prints
18/05/04 10:42:30 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Searching for l_comment:packages with top 59986052 result
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Finished searching, preparing result
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 1
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 2
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 3
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 4
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 5
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 6
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 7
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 8
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 9
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop 10
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 Loop end
18/05/04 10:42:37 INFO LuceneFineGrainDataMap: Executor task launch worker for task 0 About to searchAfter, remainingHits: 4418435, numberOfDocumentsToBeQueried: 10

And the program calls indexSearcher.searchAfter and not returning

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5633/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5637/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4479/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4494/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5654/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4731/

**Comment by ravipesala** [comment]
I have verified with 100 milliion data, and it works fine.

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5019/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6016/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4858/

**Pull request closed without merging**
