### PR TITLE
[CARBONDATA-1983] Remove unnecessary WriterVo object

### PR DESCRIPTION
**Pull request by jackylk**
While reviewing code, I found that there is an unnecessary WriterVo object created in writer, which is created in a loop. To improve that, CarbonFactDataHandlerModel can be used directly. 

 - [X] Any interfaces changed?
 No
 - [X] Any backward compatibility impacted?
 No
 - [X] Document update required?
No
 - [X] Testing done
No logic is modified
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2539/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1310/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2707/

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
