### PR TITLE
[CARBONDATA-1694] [BugFix] Resolved bug for Incorrect exception on presto CLI when a column is dropped from carbon 

### PR DESCRIPTION
**Pull request by anubhav100**
**Steps to reproduce** : same as https://issues.apache.org/jira/browse/CARBONDATA-1694

**Reason:** table key of a table still exists in carboncache of presto inside the carbontablereader class when ever we execute any alter table command  on ttha table from carbon using thrift server

**How To Verify This Pr** : same as https://issues.apache.org/jira/browse/CARBONDATA-1694

**Testing Is Done Manually** :

**Here Are Logs** 

1.**created a table in carbondata**

0: jdbc:hive2://localhost:10000> create table carbontableforalter(id int,name string) stored by 'carbondata';
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.11 seconds)
0: jdbc:hive2://localhost:10000> insert into carbontableforalter values(1,'anubhav');
+---------+--+
| Result  |
+---------+--+
+---------+--+

2. **goes to presto cli and select it**

presto:default> select * from carbontableforalter;
 id |  name   
----+---------
  1 | anubhav 
(1 row)

Query 20171110_144215_00002_yykz4, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [1 rows, 4KB] [3 rows/s, 14.3KB/s

3.**goes back to carbon and drop a column using beeline**

0: jdbc:hive2://localhost:10000> alter table carbontableforalter drop columns(id);
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.155 seconds)

0: jdbc:hive2://localhost:10000> select * from carbontableforalter;
+----------+--+
|   name   |
+----------+--+
| anubhav  |
+----------+--+
1 row selected (0.158 seconds)

4.**goes back to presto cli to select the table**

presto:default> select * from carbontableforalter;
  name   
---------
 anubhav 
(1 row)

Query 20171110_144232_00003_yykz4, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [1 rows, 4KB] [4 rows/s, 16.9KB/s]

**Dependencies**: This Pr requires #1475 to be merged first

### CODE REVIEW

**Comment by anubhav100** [comment]
@chenliang613 can you please review this pr?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/983/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1601/

**Comment by chenliang613** [comment]
verified, LGTM.
Thanks for your good contribution.

**Pull request closed without merging**
