### PR TITLE
[CARBONDATA-1013] Changes to adhere Join without dictionary column

### PR DESCRIPTION
**Pull request by srigopalmohanty**
Changes to adhere join on columns without dictionary columns.
Corresponding test cases has been checked in as well.

If two tables are joined on columns which are not dictionary columns, then unexcepcted characters are displayed.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1935/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1949/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1957/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
