### PR TITLE
[CARBONDATA-1814] Fixed bug for alter operation on tblProperties in streaming table

### PR DESCRIPTION
**Pull request by geetikagupta16**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed? No
 
 - [ ] Any backward compatibility impacted? No
 
 - [ ] Document update required? No

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1571/

**Comment by QiangCai** [comment]
please move test case to here from PR-1591

**Comment by anubhav100** [comment]
@QiangCai yes we will do it now

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1969/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1593/

**Comment by geetikagupta16** [comment]
retest this please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1989/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1594/

**Comment by QiangCai** [comment]
LGTM

**Comment by geetikagupta16** [comment]
@QiangCai I can't see my commit in the master branch. Can you please check.

**Comment by QiangCai** [comment]
@geetikagupta16 
oh, sorry, my mistake, the author is incorrect.
during mergeing, I squash the second commit to the first commit.
But I don't known the author of first commit is me.

**Pull request closed without merging**
