### PR TITLE
[CARBONDATA-1616] Documentation for Streaming Ingestion

### PR DESCRIPTION
**Pull request by sgururajshetty**
Documentation updated for streaming

> COnfiguration parameter added to enable and disable.
> Configuration parameter added for the max size
> Table properties added to show the usage along with example

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
