### PR TITLE
[CARBONDATA-1599] Optimize pull request template

### PR DESCRIPTION
**Pull request by chenliang613**
Optimize pull request template for reminding contributors to provide full information.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/366/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/491/

**Comment by lionelcao** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1120/

**Pull request closed without merging**
