### PR TITLE
[CARBONDATA-1165] solved bug for class cast exception in intermediate file merger

### PR DESCRIPTION
**Pull request by anubhav100**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/306/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2427/

**Comment by zzcclp** [comment]
LGTM, I met the same issue:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at org.apache.carbondata.processing.sortandgroupby.sortdata.IntermediateFileMerger.writeDataTofile(IntermediateFileMerger.java:347)
        at org.apache.carbondata.processing.sortandgroupby.sortdata.IntermediateFileMerger.call(IntermediateFileMerger.java:112)
        at org.apache.carbondata.processing.sortandgroupby.sortdata.IntermediateFileMerger.call(IntermediateFileMerger.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by anubhav100** [comment]
@chenliang613 he also face the same issue

**Comment by zzcclp** [comment]
@jackylk @ravipesala ping

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
