### PR TITLE
[CARBONDATA-3657]Support alter hive table add columns with complex types

### PR DESCRIPTION
**Pull request by IceMimosa**
Follow up CARBONDATA-3628 

Alter hive add columns has some problems in carbon, this PR will support:
* Map type
* Array type
* Struct type
* Decimal type with precision and scale
* Add columns with comments

### Does this PR introduce any user interface change?
 - No

 ### Is any new test case added?
 - Yes

### CODE REVIEW

**Comment by IceMimosa** [comment]
Add this please.

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1544/

**Comment by IceMimosa** [comment]
Fix style

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1546/

**Comment by IceMimosa** [comment]
Fix style

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1547/

**Comment by jackylk** [comment]
@IceMimosa This PR is ok, can you add a brief description to this PR

**Comment by IceMimosa** [comment]
@jackylk Done, thanks for reviewing.

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
