### PR TITLE
[CARBONDATA-4260][Code][summer-2021] Support CarbonData on Trino alpha

### PR DESCRIPTION
**Pull request by czy006**
### Why is this PR needed?

PrestoSQL has now changed its name to Trino. Because Facebook established the Presto Foundation at The Linux Foundation®，Led to prestosql Must be change the name. More information can see [here](https://trino.io/blog/2020/12/27/announcing-trino.html)
 
replace the old PrestoSQL implementation with a new Trino

CarbonData currently supports querying Hive/Spark data using PrestoSQL (316), but many new features and performance improvements are not available to users due to the new version of CarbonData

We will first provide a beta version of CarbonData on the summer-2021 branch. You are welcome to use the test, wait for the completion of the test and use cases, we will officially merge into the trunk branch when the functionality is stable

More information：https://issues.apache.org/jira/browse/CARBONDATA-4260

 ### What changes were proposed in this PR?

- Java 11 removed ConstructorAccessor class,use unsafe class for reflection
- Rename the file Trino beginning with Presto
- Unify file hump case style and Divide component package names
- CarbonDataSplitManager add properties serialization.lib about StorageFormatSerDe
- TrinoFilterUtil  Logical Changes to determine Rang
- Maven Pom Support Trino 358

example:
image

 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Can one of the admins verify this patch?

**Comment by Jeromestein** [comment]
Why does this PR include my irrelevant previous commit? Does anyone have an answer?

**Comment by czy006** [comment]
retest this please

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5812/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4069/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/217/

**Pull request closed without merging**
