### PR TITLE
[CARBONDATA-3074] Change default sort temp compressor to SNAPPY

### PR DESCRIPTION
**Pull request by kevinjmh**
sort temp compressor used to be set as empty, which means that Carbondata will not compress the sort temp files. This PR changes the default value to snappy.
Some experiments in local cluster shows that setting the compressor ‘snappy’ will slightly enhance the loading performance and reduce lots of disk IO during data loading.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1268/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1483/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9532/

**Comment by kevinjmh** [comment]
retest this please

**Comment by xuchuanyin** [comment]
please add description in the PR
```
Some experiments in local cluster shows that setting the compressor ‘snappy’ will slightly enhance the loading performance and reduce lots of disk IO during data loading.
```

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1271/

**Comment by xuchuanyin** [comment]
LGTM

waiting for the build

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1487/

**Pull request closed without merging**
