### PR TITLE
[CARBONDATA-1372]Update the documentation

### PR DESCRIPTION
**Pull request by xubo245**
1.   rename file path
I rename sample.csv file path in the example of documentation.   
It is more easily for users to replace the file path with their real file path of sample.csv

2. keep consistency in documentation   
Query=>Querying   
keep consistency with creating and loading

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/190/

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/194/

**Pull request closed without merging**
