### PR TITLE
[HOTFIX] Change pom version to 2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jackylk**
As CarbonData 1.6 version is released, changing version in all pom files to 2.0.0-SNAPSHOT

 - [X] Any interfaces changed?
 No
 - [X] Any backward compatibility impacted?
 No
 - [X] Document update required?
No
 - [X] Testing done
rerun all testcases
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/841/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/847/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/849/

**Comment by akashrn5** [comment]
LGTM

**Pull request closed without merging**
