### PR TITLE
[CARBONDATA-1617] Fixed atomic file operations and output stream close in Carbon index merge files

### PR DESCRIPTION
**Pull request by ravipesala**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 The merge file should be written to temp file and then renamed to actual after success. 
And output stream close to Carbon index merge files

This is extended to the PR https://github.com/apache/carbondata/pull/1436

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/796/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1429/

**Comment by jackylk** [comment]
Please update the PR description

**Comment by ravipesala** [comment]
@jackylk Added

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1098/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1699/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
