### PR TITLE
[CARBONDATA-2140 ] Refactoring code to improve performance and removing unnecessary code in Presto Integration

### PR DESCRIPTION
**Pull request by bhavya411**
This PR is for optimizing Presto performance and refactoring the code to remove unnecessary classes and making it simpler.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [X] Any interfaces changed?  No
 
 - [X] Any backward compatibility impacted?   No 
 
 - [X] Documentation Remains Same

 - [X] Testing done
     - No new test cases needed as the functionality remain same
     - All existing test cases are passing.
     - Ran the TPCH queries to check the performance .
       
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3547/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2310/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3389/

**Comment by bhavya411** [comment]
retest sdv please.

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3391/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3039/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4283/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4822/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3599/

**Comment by anubhav100** [comment]
In this PR we have removed CarbonDataRecordset, CarbonDataRecordSetProvider, and CarbonDataRecordCursor classes because now our column vectors are filled in CarbonDataPageSource, so there is no need to iterate on the record using recordcursor

**Comment by bhavya411** [comment]
This PR Removes the following classes from the PrestoCode
-CarbondataRecordCursor   - This class used to get the records row by row from the iterator, we were using this just as a placeholder for values so this class was not needed.
-CarbondataRecordSet  - This class was used to create the RecordCursor and since we were not using the Row by Row reader this class is also removed
-CarbondataRecordSetProvider - All the functionality of this class has been modularized and move to CarbondataPageSourceProvider.
- CarbondataUtil - This class was not used in the actual code.

**Comment by chenliang613** [comment]
@bhavya411 @anubhav100  Thanks for your explanation. 
LGTM

**Pull request closed without merging**
