### PR TITLE
[CARBONDATA-3962]Remove unwanted empty fact directory in case of flat_folder table

### PR DESCRIPTION
**Pull request by akashrn5**
### Why is this PR needed?
 In case of flat folder, we write the data files directly at table path, so fact dir is not required. Fact dir is unwanted and present as empty dir.
 
 ### What changes were proposed in this PR?
Remove empty fact dirs
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3881/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2140/

**Comment by kunal642** [comment]
@akashrn5 please fix the build

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2161/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3902/

**Comment by akashrn5** [comment]
@kunal642 i have fixed failures, please review and merge

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
