### PR TITLE
[CARBONDATA-3209] Remove unused import

### PR DESCRIPTION
**Pull request by WangGuangxin**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 
 - [x] Any backward compatibility impacted?
 
 - [x] Document update required?

 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by xubo245** [comment]
@WangGuangxin  Please optimize the title: [CARBONDATA-3209] Remove unused import

**Comment by xubo245** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2302/

**Comment by WangGuangxin** [comment]
> @WangGuangxin Please optimize the title: [CARBONDATA-3209] Remove unused import

Done

**Comment by xubo245** [comment]
LGTM

**Comment by zzcclp** [comment]
LGTM

**Comment by xubo245** [comment]
@WangGuangxin Thank you for working on it.

**Pull request closed without merging**
