### PR TITLE
[CARBONDATA-1597] Remove spark1 integration

### PR DESCRIPTION
**Pull request by jackylk**
As voted by community, spark version 1 integration can be removed.
This PR removes following profiles and module for spark version 1 integration
1. spark-1.5 profile
2. spark-1.6 profile
3. example/spark module
4. integration/spark module

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/361/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1114/

**Comment by sraghunandan** [comment]
LGTM

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
