### PR TITLE
[CARBONDATA-1444] Update documentation about Boolean data type

### PR DESCRIPTION
**Pull request by xubo245**
Add BOOLEAN data type into "supported-data-types-in-carbondata" documentation

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1293/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/656/

**Comment by chenliang613** [comment]
@sgururajshetty  please review it.

**Comment by sgururajshetty** [comment]
LGTM

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
