### PR TITLE
[CARBONDATA-1255]-updated "ddl-operation-on-carbondata.md" for column_group feature

### PR DESCRIPTION
**Pull request by vandana7**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/291/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2875/

**Comment by sgururajshetty** [comment]
@vandana7 this feature is getting removed from the code. We dont need this anymore.

**Comment by chenliang613** [comment]
Please find the mailing list discussion : 
http://apache-carbondata-dev-mailing-list-archive.1130556.n5.nabble.com/About-ColumnGroup-feature-td14436.html

**Comment by sgururajshetty** [comment]
LGTM

**Pull request closed without merging**
