### PR TITLE
[CARBONDATA-1024] added support for float data type in hive

### PR DESCRIPTION
**Pull request by anubhav100**
added support for float data type in hive
check manually using hive cli

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1968/

**Comment by anubhav100** [comment]
@chenliang613 now i tested it manually as well with latest code can you merge it here are logs to verify
 
INSIDE SPARK SHELL 
scala> carbon.sql("create table floattest(name string,salary float) stored by 'carbondata'")

scala> carbon.sql("""load data inpath 'hdfs://localhost:54310/floatypetest.csv' into table floattest""").show

scala> carbon.sql("""SELECT * FROM floattest""").show
+-------+-------+
|   name| salary|
+-------+-------+
|ANUBHAV|20000.0|
|  LIANG|  2.0E7|
+-------+-------+

INSIDE HIVE SHELL

hive> create table floattesthive(NAME string,salary float);
OK
Time taken: 0.283 seconds
hive> ALTER TABLE FLOATTESTHIVE SET FILEFORMAT
    > INPUTFORMAT "org.apache.carbondata.hive.MapredCarbonInputFormat"
    > OUTPUTFORMAT "org.apache.carbondata.hive.MapredCarbonOutputFormat"
    > SERDE "org.apache.carbondata.hive.CarbonHiveSerDe";
OK
Time taken: 0.386 seconds
hive> ALTER TABLE floattesthive SET LOCATION 'hdfs://localhost:54310/opt/carbonStore/default/floattest' ;
OK
Time taken: 0.414 seconds
hive> select * from floattesthive;
OK
ANUBHAV	20000.0
LIANG	2.0E7
Time taken: 0.085 seconds, Fetched: 2 row(s)

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2208/

**Comment by asfgit** [comment]
Tests Passed for Spark1.6

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/76/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2214/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/84/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/84/org.apache.carbondata$carbondata-spark-common-test/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/84/org.apache.carbondata$carbondata-spark-common-test/testReport/org.apache.carbondata.spark.testsuite.allqueries/InsertIntoCarbonTableTestCase/insert_into_carbon_table_from_carbon_table_union_query/'><strong>org.apache.carbondata.spark.testsuite.allqueries.InsertIntoCarbonTableTestCase.insert into carbon table from carbon table union query</strong></a></li></ul>

**Comment by anubhav100** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/85/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/85/org.apache.carbondata$carbondata-spark-common-test/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/85/org.apache.carbondata$carbondata-spark-common-test/testReport/org.apache.carbondata.spark.testsuite.allqueries/InsertIntoCarbonTableTestCase/insert_into_carbon_table_from_carbon_table_union_query/'><strong>org.apache.carbondata.spark.testsuite.allqueries.InsertIntoCarbonTableTestCase.insert into carbon table from carbon table union query</strong></a></li></ul>

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2216/

**Comment by anubhav100** [comment]
I am closing this pr I have raised another pr for this issue

https://github.com/apache/carbondata/pull/1326

**Pull request closed without merging**
