### PR TITLE
[CARBONDATA-2404] Add documentation for using carbondata and stored as carbondata

### PR DESCRIPTION
**Pull request by xubo245**
Add documentation for:
1.using carbondata
2.stored as carbondata, and add test case in carbonSessionExample

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 No
 - [x] Any backward compatibility impacted?
 No
 - [x] Document update required?
Yes
 - [x] Testing done
 Yes,in Add documentation for using carbondata and stored as carbondata
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
https://github.com/apache/carbondata/pull/2078
https://github.com/apache/carbondata/pull/2081

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4251/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5419/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4557/

**Comment by xubo245** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4278/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5445/

**Comment by xubo245** [comment]
@chenliang613 Please review it

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
