### PR TITLE
[CARBONDATA-3077] Fixed query failure in fileformat due stale cache issue

### PR DESCRIPTION
**Pull request by manishgupta88**
**Problem**
While using FileFormat API, if a table created, dropped and then recreated with the same name the query fails because of schema mismatch issue

**Analysis**
In case of carbondata used through FileFormat API, once a table is dropped and recreated with the same name again then because the dataMap contains the stale carbon table schema mismatch exception is thrown

**Solution**
To avoid such scenarios it is always better to update the carbon table object retrieved

 - [ ] Any interfaces changed?
No 
 - [ ] Any backward compatibility impacted?
 No
 - [ ] Document update required?
No
 - [ ] Testing done
Added UT to verify the scenario
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by xuchuanyin** [comment]
I think the current modification does not fix the root of the problem. If you think the table information is not get cleared, you should get it cleared, not just update it when you need it.
The current implementation means at some time, the table information is kept somewhere as outdated.

**Comment by manishgupta88** [comment]
@xuchuanyin ...your point is correct. To explain this in detail
1. We have already a way to clear the cached DataMaps through API call `DataMapStoreManager.getInstance().clearDataMaps(AbsoluteTableIdentifier identifier)`. This API call ensures that for a given table all the dataMaps are cleared.
2. For FileFormat case if the above API is not integrated by the customer there is a possibility that drop table call will not come to carbondata layer and there can be few stale objects which can cause query failure. 
The PR is raised to handle the 2nd case. The other stale DataMaps are being already taken care by the LRU cache which will clear the stale entries one LRU cache threshold is reached.
Let me know if you still have doubts

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9540/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1278/

**Comment by manishgupta88** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1289/

**Comment by xuchuanyin** [comment]
@manishgupta88 What if the user use fileformat carbontable and normal carbontable at the same time? For example, creating/using/droping fileformat table and then creating/using/droping normal carbon table, these tables are with the same name. Will this be OK?

**Comment by manishgupta88** [comment]
@xuchuanyin ...yes this scenario will work fine. In case of dropping normal table it will go through CarbonSession flow and drop table command is already taking care of clearing the datamaps.
In case of fileFormat table drop, if the clear dataMap API is not integrated by customer in that case the changes done in this PR will take care of referring only to latest carbon table

**Comment by manishgupta88** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1511/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1300/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9561/

**Comment by manishgupta88** [comment]
retest this please

**Comment by ravipesala** [comment]
@manishgupta88 it solves part of the problem (schema mismatch issue). But when you call getDataMaps it will give stale datamaps to you right.  How those can be updated?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1306/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1521/

**Comment by ravipesala** [comment]
@manishgupta88 I am referring to `DataMapFactory.getDataMaps(List<Segment> segments)` . If already cached with old table then who invalidates them. For new table also it gets the old datamaps right.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9569/

**Comment by manishgupta88** [comment]
@ravipesala ....in this method we are passing the `List<Segment>` . The list contains the segments file only from the new table. So only the new index files will be loaded and queried and the same is covered in test case added as part of this PR.
The stale dataMap entries will never be referred. For clearing them we need to configure the LRU cache size which will automatically take care of eviction when threshold is reached. If LRU cache size is not configured then there is no mechanism to clear the stale datamaps

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1310/

**Comment by ravipesala** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1383/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9641/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1593/

**Comment by brijoobopanna** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1395/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1604/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9652/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
