### PR TITLE
[CARBONDATA-1626] Documentation for add datasize and index size to table status file

### PR DESCRIPTION
**Pull request by sgururajshetty**
Added the parameter to add data size and index size to the table status.

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
