### PR TITLE
[CARBONDATA-TEST] jenkins test

### PR DESCRIPTION
**Pull request by shenjiayu17**
### Why is this PR needed?
 Todo
 
 ### What changes were proposed in this PR?
Todo
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6369/

**Comment by shenjiayu17** [comment]
retest this please

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/754/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6370/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4658/

**Comment by jbonofre** [comment]
I'm working on fixing Jenkins. For now, I have an issue to build locally on my machine. I will create few PRs about that.

**Pull request closed without merging**
