### PR TITLE
[CARBONDATA-1207] Resource leak problem in CarbonDictionaryWriter

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2630/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/539/

**Comment by gvramana** [comment]
LGTM

**Pull request closed without merging**
