### PR TITLE
[CARBONDATA-1314] Fix scalatest issues

### PR DESCRIPTION
**Pull request by chenliang613**
Fix scalatest issues, as below : 
Error:(238, 16) can't expand macros compiled by previous versions of Scala
        assert(false)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/521/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3112/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
