### PR TITLE
[CARBONDATA-1965]removed sort_scope from dynamic configuration in carbondata using set-reset as it is not configured by set

### PR DESCRIPTION
**Pull request by vandana7**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1440/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2674/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2812/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
