### PR TITLE
[Documentation] Single pass condition for high cardinality

### PR DESCRIPTION
**Pull request by sgururajshetty**
Added the information that when single pass is used, then high cardinality enable property will be disabled during the data load.

### CODE REVIEW

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
@chenliang613 please review and merge

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/89/

**Comment by chenliang613** [comment]
@QiangCai  please review this PR, thanks.

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
