### PR TITLE
[CARBONDATA - 1159] Batch sort loading is not proper without synchronization

### PR DESCRIPTION
**Pull request by dhatchayani**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/292/

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2414/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
