### PR TITLE
 [CARBONDATA-1922] Documentation - Updated document with Ignoring empty line OPTION

### PR DESCRIPTION
**Pull request by brahmareddybattula**
Documentation - Updated document with Ignoring empty line OPTION

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
LGTM

**Comment by brahmareddybattula** [comment]
thanks @jackylk  for reviewing and committing,jira isn't assigned to me,can you assign? @ravipesala thanks for taking look into this.

**Pull request closed without merging**
