### PR TITLE
[CARBONDATA-980] Fix for Is Not Null in presto

### PR DESCRIPTION
**Pull request by jatin9896**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2877/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/293/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
