### PR TITLE
[CARBONDATA-2109]make configs of dataframe load with tempCSV valid ,such as QUOTECHAR

### PR DESCRIPTION
**Pull request by qiuchenjian**
use datafame to load data with tempCSV true(dataset.writer..format("carbondata").save), carbondata will generate sql to load data
the sql's configs only have SINGLE_PASS, other configs is invalid,such as QUOTECHAR.
the code is in CarbonDataFrameWriter:

private def makeLoadString(csvFolder: String, options: CarbonOption): String = {
val dbName = CarbonEnv.getDatabaseName(options.dbName)(sqlContext.sparkSession)
s"""

LOAD DATA INPATH '$csvFolder'
INTO TABLE $dbName.${options.tableName}
OPTIONS ('FILEHEADER' = '${dataFrame.columns.mkString(",")}',
'SINGLE_PASS' = '${options.singlePass}')
""".stripMargin
}

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 No
 - [ ] Any backward compatibility impacted?
 No
 - [ ] Document update required?
No
 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       Y
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3350/

**Comment by qiuchenjian** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3378/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2141/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3276/

**Comment by xuchuanyin** [comment]
No need to fix this. I think the 'tempCSV' option has other underlying problems, so it's better to deprecate this option. Pls refer to [CARBONDATA-2110](https://issues.apache.org/jira/browse/CARBONDATA-2110).

**Comment by qiuchenjian** [comment]
@xuchuanyin , I agree, this 'tempCSV' option has serveral bugs to fix

**Comment by qiuchenjian** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2181/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3419/

**Comment by jackylk** [comment]
Please close this PR if not required

**Pull request closed without merging**
