### PR TITLE
[CARBONDATA-1599] Update pull request checklist

### PR DESCRIPTION
**Pull request by chenliang613**
Remove "title and description" items from pull request checklist, add  them to How to contribute document.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/735/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1372/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/736/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1373/

**Comment by jackylk** [comment]
LGTM

**Comment by jackylk** [comment]
@ravipesala @kumarvishal09 @QiangCai please have a look

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
