### PR TITLE
[WIP] Fix the result of inspecting code in Intellij IDEA

### PR DESCRIPTION
**Pull request by QiangCai**
### Why is this PR needed?
 1. pointless bitwise expression
2. field can be local
3. standard Charset object can be used
4. unecessary conversion to String
5. unecessary interface modifier
6. unecessary semicolon
7. duplicate condition in 'if' statement
8. 'if' statement with common parts 
9. Redundant 'if' statement
10. unnecessary 'null' check before method call
11. Redundant local variable
12. unused import
 ### What changes were proposed in this PR?

    
 ### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1391/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3115/

**Comment by ajantha-bhat** [comment]
@QiangCai : you are going through every file by file and doing it ? big work!

**Comment by QiangCai** [comment]
@ajantha-bhat Intellij Idea has this function in menu Analyze/inspect code, it will output a report which can be improved. I hope to check all suggestions in the report one by one and fix them.

**Pull request closed without merging**
