### PR TITLE
[carbondata-1149] Fix issue of mismatch type of partition column when specify partition info

### PR DESCRIPTION
**Pull request by chenerlu**
Background:
Create a partition table with invalid partition info (numPartitions, range info and list info) will success. Actually, create table operation should failed as expected.

Root cause:
There is no check mechanism for partition info when create a partition table.

Solution:
Add check mechanism for partition info when create a partition table. If the partition info is invalid, an exception will be throwed and create table operation will fail.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2535/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/423/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2536/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/425/

**Comment by gvramana** [comment]
LGTM

**Pull request closed without merging**
