### PR TITLE
[CARBONDATA-4261][Doc][summer-2021] Add new ways of "contact us" in README.md

### PR DESCRIPTION
**Pull request by Jeromestein**
### Why is this PR needed?
 To update new ways of contacting our community.
 
 ### What changes were proposed in this PR?
1. Add a Slack link and WeChat QR Code in README.md.
2. Add QRCode_WechatGroup.png to carbondata/docs/images/ .
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

    
JIRA Issue: https://issues.apache.org/jira/browse/CARBONDATA-4261

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Can one of the admins verify this patch?

**Comment by Jeromestein** [comment]
Actually, do more changes and updates in this (https://github.com/apache/carbondata/pull/4191) based on this PR.

**Comment by chenliang613** [comment]
looks good to me

**Comment by brijoobopanna** [comment]
add to whitelist

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4065/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/213/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5808/

**Pull request closed without merging**
