### PR TITLE
[CARBONDATA-3429] Updated error for CarbonCli when path is wrong

### PR DESCRIPTION
**Pull request by NamanRastogi**
**Problem**: Execute CarbonCli with an invalid path. The output even for invalid path is "unsorted", which is wrong. 

**Solution**: It should throw that it segment path is invalid.

 - [x] Any interfaces changed?  ->  No
 - [x] Any backward compatibility impacted?  ->  No
 - [x] Document update required?  ->  No
 - [x] Testing done  ->  Yes
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3524/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3729/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11796/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
