### PR TITLE
[CARBONDATA-612]throw exception when trying to use bucketing in spark 1.6

### PR DESCRIPTION
**Pull request by anubhav100**
in spark 1.6 when we try to create a bucketed table it do not give any exception but it should as bucketing is not supported in spark 1.6 in this pr this functionality is provided

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/581/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/582/

**Comment by jackylk** [comment]
Oh, I thought it is supported. Why bucket table is not supported in spark1.6?

**Comment by ravipesala** [comment]
@anubhav100  bucket is supported in all spark versions, but we will not get the benefit of join optimization in 1.6 and 1.5.

**Comment by anubhav100** [comment]
@ravipesala but it does not validate anycheck if it is supported even if  we will not get the benefit of join optimization all carbondata checks must be validated

**Comment by chenliang613** [comment]
@anubhav100  the feature would be supported in all versions, but only be suggested using in spark 2.1 for getting ideal performance.

**Comment by Zhangshunyu** [comment]
I think it would be better to give an info about the difference instead of throw such an exception.

**Comment by anubhav100** [comment]
@Zhangshunyu u mean we should display the info to user that bucketing join benefit is in spark 2.1

**Comment by chenliang613** [comment]
please change the title as per the format: [CARBONDATA-issue number>] Title of the pull request (need to add a blank)

**Comment by CarbonDataQA** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/64/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/633/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1264/

**Pull request closed without merging**
