### PR TITLE
[CARBONDATA-3853] Data load failure when loading with bucket column as DATE data type

### PR DESCRIPTION
**Pull request by maheshrajus**
[CARBONDATA-3853] Data load failure when loading with bucket column as DATE data type

 ### Why is this PR needed?
 While loading data into a table which has bucket column as DATE data type then receiving data load failure due to class-cast exception. The class-cast exception is due to DATE data type is not going as IntegralHash type for getting the hash because of there is no case for DATE datatype and it is going for StringHash type and typecast results class-cast Exception.
 
 ### What changes were proposed in this PR?
Added a OR (||) condition if data type is DATE then it will go IntegralHash getHash() method for getting the hash code.   
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3331/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1591/

**Comment by Zhangshunyu** [comment]
LGTM

**Comment by ajantha-bhat** [comment]
LGTM

**Pull request closed without merging**
