### PR TITLE
[CARBONDATA-1993] Removed unused carbon properties high.cardinality.identify…

### PR DESCRIPTION
**Pull request by pawanmalwal**
Removed carbon properties high.cardinality.identify.enable and high.cardinality.threshold

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [X] Any interfaces changed?
 None
 - [X] Any backward compatibility impacted?
 None
 - [X] Document update required?
Removed references from document file
 - [X] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       NA
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
None

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1398/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2633/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2796/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
