### PR TITLE
[CARBONDATA-3855]support carbon SDK to load data from different files

### PR DESCRIPTION
**Pull request by nihal0107**
### Why is this PR needed?
 TO support carbon SDK to load data from different files.
 
### What changes were proposed in this PR?

Now user can load a single file or all files under a given directory or selected files under given directory.

Please go through the design document for better understanding-
https://issues.apache.org/jira/browse/CARBONDATA-3855
    
### Does this PR introduce any user interface change?
 - No

### Is any new test case added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1519/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3249/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3254/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3259/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1523/

**Comment by brijoobopanna** [comment]
@nihal0107 please elobrate the PR description as it a requirement, check some old requirement PR such as 3478

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1542/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3279/

**Pull request closed without merging**
