### PR TITLE
[Sync PR 2149][CARBONDATA-2381] Changes taken from PR 2149 for compaction to enable reading at blocklet level and page uncompression at page level

### PR DESCRIPTION
**Pull request by manishgupta88**
Code synced from PR #2149 for compaction performance. Using this code compaction will perform IO at blocklet level and uncompression at page level

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by jackylk** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4155/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5335/

**Comment by manishgupta88** [comment]
PR #2149 already merged in master

**Pull request closed without merging**
