### PR TITLE
[CARBONDATA-1137]updated ddl operation-on-carbondata.md for SORT_COLUMNS

### PR DESCRIPTION
**Pull request by vandana7**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/651/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3246/

**Comment by sgururajshetty** [comment]
LGTM
@chenliang613 kindly review

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3303/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/707/

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
