### PR TITLE
[CARBONDATA-1931]DataLoad failed for Aggregate table when measure is …

### PR DESCRIPTION
**Pull request by BJangir**
Root Cause  , during data loading ,dataframe columns are sorted based on selection order but  in RowConverter fileds values are compared based on ordinal column .

Solution  = while making CarbonLoadModel set header sorted by ordinal columns instead of selection order.

### CODE REVIEW

**Comment by gvramana** [comment]
add to whitelist

**Comment by kunal642** [comment]
retest this please

**Comment by gvramana** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2518/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2267/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1046/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1058/

**Comment by kumarvishal09** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2314/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1098/

**Comment by BJangir** [comment]
Merged

**Pull request closed without merging**
