### PR TITLE
[CARBONDATA-1301] change command to update schema and data separately

### PR DESCRIPTION
**Pull request by jackylk**
In this PR, all commands are changed to extend from `SchemaUpdatableCommand` or `DataProcessCommand`:

`SchemaUpdatableCommand` indicates that the command will modify schema
`DataProcessCommand` indicates that the command will modify(add/delete) data in HDFS

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/436/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3024/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/453/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3041/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/456/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3045/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
