### PR TITLE
[HOTFIX] Fix NPE on windows

### PR DESCRIPTION
**Pull request by kevinjmh**
*Problem*

#3339 has some changes in `CarbonFileMetastore.createCarbonRelation`, running query on windows will fail as follow:
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.carbondata.core.datamap.TableDataMap.prune(TableDataMap.java:122)
	at org.apache.carbondata.hadoop.api.CarbonInputFormat.getPrunedBlocklets(CarbonInputFormat.java:558)
	at org.apache.carbondata.hadoop.api.CarbonInputFormat.getDataBlocksOfSegment(CarbonInputFormat.java:471)
	at org.apache.carbondata.hadoop.api.CarbonTableInputFormat.getSplits(CarbonTableInputFormat.java:460)
	at org.apache.carbondata.hadoop.api.CarbonTableInputFormat.getSplits(CarbonTableInputFormat.java:196)
	at org.apache.carbondata.spark.rdd.CarbonScanRDD.internalGetPartitions(CarbonScanRDD.scala:131)
```

*Analyse*

carbon index files are merged but `SegmentFile` did not update, so it fails to get any default datamap for pruning. 

The reason for no updated is about path comparison like `/[your_path_here]/examples/spark2/target/store/default/source/\Fact\Part0\Segment_0` 

vs

 `D:/[your_path_here]/examples/spark2/target/store/default/source/Fact/Part0/Segment_0`

the main different is disk symbol

*Solution*

use the `AbsoluteTableIdentifier` of table from `CarbonMetadata` instead of the newly created object, keep the path style same

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/423/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/425/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/425/

**Comment by kevinjmh** [comment]
@kunal642 Please check

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
