### PR TITLE
[CARBONDATA-2216][Test] Fix bugs in sdv tests

### PR DESCRIPTION
**Pull request by xuchuanyin**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 `NO`
 - [x] Any backward compatibility impacted?
  `NO`
 - [x] Document update required?
 `NO`
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3977/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2733/

**Comment by jackylk** [comment]
LGTM

**Comment by jackylk** [comment]
merged into datamap branch

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3734/

**Comment by xuchuanyin** [comment]
@ravipesala The sdvtest complains that 
```
Error Message
2 did not equal 1
Stacktrace
      org.scalatest.exceptions.TestFailedException: 2 did not equal 1
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
      at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
      at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
      at org.apache.carbondata.cluster.sdv.generated.MergeIndexTestCase$$anonfun$3.apply$mcV$sp(MergeIndexTestCase.scala:97)
```
But actually I cloned the `sdv-test_data` branch in your repo and tested it in local, the dataloading only generated 1 *.index file not 2.

Is there any different from the CI env and Local env?

**Pull request closed without merging**
