### PR TITLE
[Doc] Update README.md: : syntax and format issues

### PR DESCRIPTION
**Pull request by Sunt-ing**
### Why is this PR needed?
 To improve the quality of the readme file.
 
 ### What changes were proposed in this PR?
Typo and inconsistent format 
    
 ### Does this PR introduce any user interface change?
 - No 

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Can one of the admins verify this patch?

**Comment by ajantha-bhat** [comment]
Add to whitelist

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3624/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5369/

**Comment by Sunt-ing** [comment]
@chenliang613 Hello, could you please review this PR? I think it should be very easy for you to review. Thanks!

**Pull request closed without merging**
