### PR TITLE
 [ISSUE-4298] Fixed mail list issue

### PR DESCRIPTION
**Pull request by xubo245**
### Why is this PR needed?
 Can't open the mail list, we should fixed it.
 https://github.com/apache/carbondata/pull/4300
 ### What changes were proposed in this PR?
change the mail list address
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No, only change the document

### CODE REVIEW

**Comment by chenliang613** [comment]
LGTM

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6376/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4667/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/759/

**Pull request merged**
