### PR TITLE
[Don't merge] Only for test apache jenkin CIs, to avoid printing too much error msg.

### PR DESCRIPTION
**Pull request by chenliang613**
This PR is making test case failed, to check if print too much error msg after configuring jenkins CI

### CODE REVIEW

**Comment by ravipesala** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/816/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/740/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/740/org.apache.carbondata$carbondata-spark-common-test/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/740/org.apache.carbondata$carbondata-spark-common-test/testReport/org.apache.carbondata.spark.testsuite.aggquery/IntegerDataTypeTestCase/select_empno_from_integertypetableAgg/'><strong>org.apache.carbondata.spark.testsuite.aggquery.IntegerDataTypeTestCase.select empno from integertypetableAgg</strong></a></li></ul>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-2.1/88/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='carbondata-pr-spark-2.1/org.apache.carbondata:carbondata-spark-common-test' /><a href='https://builds.apache.org/job/carbondata-pr-spark-2.1/88/org.apache.carbondata$carbondata-spark-common-test/testReport'>carbondata-pr-spark-2.1/org.apache.carbondata:carbondata-spark-common-test</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-2.1/88/org.apache.carbondata$carbondata-spark-common-test/testReport/org.apache.carbondata.spark.testsuite.aggquery/IntegerDataTypeTestCase/select_empno_from_integertypetableAgg/'><strong>org.apache.carbondata.spark.testsuite.aggquery.IntegerDataTypeTestCase.select empno from integertypetableAgg</strong></a></li></ul>

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/138/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3406/

**Comment by jbonofre** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/823/

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/141/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/158/

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/244/

**Comment by jackylk** [comment]
@chenliang613 close this if not needed anymore

**Pull request closed without merging**
