### PR TITLE
[CARBONDATA-2777] Fixed: NonTransactional tables, Select count(*) is not giving latest results for incremental load with same segment ID (UUID)

### PR DESCRIPTION
**Pull request by ajantha-bhat**
problem:
[CARBONDATA-2777] NonTransactional tables, Select count(*) is not giving latest results for incremental load with same segment ID (UUID)

solution:
For NonTransactional tables, segments need to be refreshed if the segment latest timestamp got changed by the incremental load for count(*) flow also. This change is already present in select * flow and missed here.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed? NA
 
 - [ ] Any backward compatibility impacted? NA
 
 - [ ] Document update required? NA

 - [ ] Testing done
done. Updated UT.

 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7451/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/6210/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5984/

**Comment by ajantha-bhat** [comment]
@ravipesala : please review

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
