### PR TITLE
[CARBONDATA-4227] SDK CarbonWriterBuilder cannot execute `build()` several times with different output path

### PR DESCRIPTION
**Pull request by IceMimosa**
## Why is this PR needed?

Sometimes we want to reuse the CarbonWriterBuilder object to build CarbonWriter with different output paths, but it does not work.

For example:

```kotlin
val builder = CarbonWriter.builder().withCsvInput(...).writtenBy(...)

// 1. first writing with path1
val writer1 = builder.outputPath(path1).build()
// write data, it works 

// 2. second writing with path2
val writer2 = builder.outputPath(path2).build()
// write data, it does not work. It still writes data to path1
```

## Does this PR introduce any user interface change?
No

## Is any new testcase added?
Yes

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5613/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3868/

**Comment by IceMimosa** [comment]
How do I login to Jenkins？

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/2/

**Comment by ydvpankaj99** [comment]
retest this please

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3875/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/22/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3879/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5620/

**Comment by IceMimosa** [comment]
retest this please

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5624/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3881/

**Pull request closed without merging**
