### PR TITLE
[CARBONDATA-2571] Calculating the carbonindex and carbondata file size of a table is wrong

### PR DESCRIPTION
**Pull request by dhatchayani**
**Problem:**
While calculating the carbonindex files size, we are checking either index file or merge file. But in PR#2333, implementation is changed to fill both the file name and the merge file name. So, we have to consider both fields.
**Solution:**
While calculating the carbonindex files size, we have to consider both the files and mergeFileName fields. We should get the list of index files from these 2 fields and then calculate the size of the files.

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [x] Testing done
        Manual Testing
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6231/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5068/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5203/

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
