### PR TITLE
DOCUMENTATION - Removed unused parameters, added SORT_SCOPE, and updated dictionary details

### PR DESCRIPTION
**Pull request by sgururajshetty**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
@PallaviSingh1992 please review for the formatting as per the rule and confirm

**Comment by PallaviSingh1992** [comment]
@sgururajshetty The formatting is correct.

**Comment by sgururajshetty** [comment]
@chenliang613 please review

**Comment by chenliang613** [comment]
@sgururajshetty  please add scenarios info for SORT_SCOPE

**Pull request closed without merging**
