### PR TITLE
[CARBONDATA-2110]deprecate 'tempCSV' option of dataframe load

### PR DESCRIPTION
**Pull request by qiuchenjian**
deprecate 'tempCSV' option of dataframe load, it won't generate temp file on hdfs,  no matter the value of tempCSV
@jackylk

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3452/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2212/

**Comment by qiuchenjian** [comment]
@jackylk ，fix bugs as mentioned

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3321/

**Comment by jackylk** [comment]
Can you search for tempCSV in all testcases and delete them, I think you can do it easily in IDE

**Comment by qiuchenjian** [comment]
I think the tests with tempCSV need be kept, because the customer is still using the option @jackylk

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
