### PR TITLE
[CARBONDATA-1326]- Findbugs Fixes

### PR DESCRIPTION
**Pull request by kapilreja**
Find-bugs Fixes

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by sraghunandan** [comment]
LGTM

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by kapilreja** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
