### PR TITLE
[CARBONDATA-2234] Support UTF-8 with BOM in CSVInputFormat

### PR DESCRIPTION
**Pull request by KanakaKumar**
Currently Hive table supports csv file with BOM encoding but Carbon table does not support.
 org.apache.hadoop.mapred.LineRecordReader handles the BOM bytes but CSVInputFormat has not handled. We can use BomInputStream to identify and skip the BOM bytes.

Checklist:
 - [ ] Any interfaces changed?
 NA
 - [ ] Any backward compatibility impacted?
 NA. Even if there is no BOM bytes, CSV reading works fine.
 - [ ] Document update required?
NA
 - [x] Testing done
        UT added with non compressed and compressed CSV files.
     
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2873/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4118/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2876/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4122/

**Comment by KanakaKumar** [comment]
retest SDV please

**Comment by gvramana** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3783/

**Pull request closed without merging**
