### PR TITLE
[CARBONDATA-1419] Support adaptive encoding for Double data type

### PR DESCRIPTION
**Pull request by jackylk**
Add a new encoding for Double data type:
1. AdaptiveFloatingCodec, it will multiple the column value by Math.pow(10, decimalCount) and do type cast from double to target data type like byte, short, int

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/303/

**Comment by CarbonDataQA** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/305/

**Comment by CarbonDataQA** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/309/

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
I have merged but still not closed, Please close it manually

**Pull request closed without merging**
