### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Karan-c980**
### Why is this PR needed?
 
 
 ### What changes were proposed in this PR?

    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Can one of the admins verify this patch?

**Comment by ajantha-bhat** [comment]
Add to whitelist

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by ajantha-bhat** [comment]
@Karan-c980 : please keep in [WIP] and push the changes once done

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1031/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2744/

**Comment by kunal642** [comment]
@Karan-c980 What is this PR for?

**Comment by jackylk** [comment]
please create JIRA to discuss before raising PR.
close this PR please

**Pull request closed without merging**
