### PR TITLE
[CARBONDATA-1191] Remove carbon-spark-shell script

### PR DESCRIPTION
**Pull request by chenerlu**
As discuss in mailing list, we reach an agreement to remove this useless feature.
So this PR is removing related class.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2582/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/479/

**Comment by chenliang613** [comment]
LGTM

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
