### PR TITLE
[CARBONDATA-1118] Inset Filter Pushdown in 2.1

### PR DESCRIPTION
**Pull request by sounakr**
Inset Filter PushDown.

### CODE REVIEW

**Comment by chenliang613** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-2.1/49/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2155/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/20/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
