### PR TITLE
[Documentation] Editorial review

### PR DESCRIPTION
**Pull request by sgururajshetty**
Corrected spelling mistakes and grammer

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1584/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1796/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9843/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
