### PR TITLE
[CARBONDATA-1281] Support multiple temp dirs for writing files while loading data

### PR DESCRIPTION
**Pull request by xuchuanyin**
# Modifications
This feature mainly focus on avoiding disk hot-spot in single massive data loading, changes are made in two parts: 

1. randomly choose a yarn local folder while writing sort temp file each time in sort-process;

2.randomly choose a yarn local folder while writing carbondata file each time in write-process.

# Usage

To enable this feature, user should enable `carbon.use.multi.temp.dir=true` and `carbon.use.local.dir=true`.

# Performance
In my case, this feature improves the loading performance from 35M/s/node to 70+M/s/node

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3188/

**Comment by xuchuanyin** [comment]
This PR is the same as #1177 
#1177 contains to many commits, so I use a new PR and squash the commits

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/593/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/594/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3189/

**Comment by xuchuanyin** [comment]
@sraghunandan @chenliang613 @bill1208  Thanks for your reviews. The changes for the reviews are in commit: https://github.com/xuchuanyin/carbondata/commit/92637c6035358b3cc354966d2dc29e1003f387dd

**Comment by chenliang613** [comment]
@xuchuanyin  everything looks ok, please do rebase.

**Comment by xuchuanyin** [comment]
@chenliang613 
Sorry for adding irrelevant commits to this PR by uncorrected rebasing. :disappointed: 

I've created a new PR #1198 for this.

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/603/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3198/

**Comment by xuchuanyin** [comment]
@chenliang613 This PR contains commits from the others by uncorrected rebasing. So I close it and create a new one #1198

**Pull request closed without merging**
