### PR TITLE
Merging datamap branch into master

### PR DESCRIPTION
**Pull request by jackylk**
This PR includes all commit from datamap branch:
[CARBONDATA-2172][Lucene] Add text_columns property for Lucene DataMap (5 minutes ago) <QiangCai>
[REBASE] Fix style after rebasing master (12 hours ago) <Jacky Li>
[CARBONDATA-2216][Test] Fix bugs in sdv tests (12 hours ago) <xuchuanyin>
[CARBONDATA-2213][DataMap] Fixed wrong version for module datamap-example (12 hours ago) <xuchuanyin>
[CARBONDATA-2206] Fixed lucene datamap evaluation issue in executor (12 hours ago) <ravipesala>
[CARBONDATA-2206] support lucene index datamap (12 hours ago) <Jacky Li>
[HOTFIX] Fix timestamp issue in TestSortColumnsWithUnsafe (12 hours ago) <Jacky Li>
[HOTFIX] Add dava doc for datamap interface (12 hours ago) <Jacky Li>
[CARBONDATA-2189] Add DataMapProvider developer interface (12 hours ago) <Jacky Li>
[CARBONDATA-1543] Supported DataMap chooser and expression for supporting multiple datamaps in single query (13 hours ago) <Ravindra Pesala>
[REBASE] Solve conflict after merging master (14 hours ago) <Jacky Li>
[CARBONDATA-1114][Tests] Fix bugs in tests in windows env (14 hours ago) <xuchuanyin>
[CARBONDATA-2091][DataLoad] Support specifying sort column bounds in data loading (14 hours ago) <xuchuanyin>
[CARBONDATA-2186] Add InterfaceAudience.Internal to annotate internal interface (14 hours ago) <Jacky Li>
[HOTFIX] Support generating assembling JAR for store-sdk module (14 hours ago) <Jacky Li>
[CARBONDATA-2023][DataLoad] Add size base block allocation in data loading (14 hours ago) <xuchuanyin>
[CARBONDATA-2018][DataLoad] Optimization in reading/writing for sort temp row (14 hours ago) <xuchuanyin>
[CARBONDATA-2159] Remove carbon-spark dependency in store-sdk module (14 hours ago) <Jacky Li>
[CARBONDATA-1997] Add CarbonWriter SDK API (14 hours ago) <Jacky Li>
[CARBONDATA-2156] Add interface annotation (14 hours ago) <Jacky Li>
[REBASE] resolve conflict after rebasing to master (14 hours ago) <Jacky Li>
[REBASE] Solve conflict after rebasing master (14 hours ago) <Jacky Li>
[HotFix][CheckStyle] Fix import related checkstyle (14 hours ago) <xuchuanyin>
[CARBONDATA-1544][Datamap] Datamap FineGrain implementation (14 hours ago) <ravipesala>
[CARBONDATA-1480]Min Max Index Example for DataMap (14 hours ago) <sounakr>
[CARBONDATA-2080] [S3-Implementation] Propagated hadoopConf from driver to executor for s3 implementation in clustermode. (14 hours ago) <Jatin>
[CARBONDATA-2025] Unify all path construction through CarbonTablePath static method (14 hours ago) <Jacky Li>
[CARBONDATA-2099] Refactor query scan process to improve readability (14 hours ago) <Jacky Li>
[REBASE] Solve conflict after rebasing master (14 hours ago) <Jacky Li>
[CARBONDATA-1827] S3 Carbon Implementation (14 hours ago) <SangeetaGulia>
[CARBONDATA-1968] Add external table support (14 hours ago) <Jacky Li>
[CARBONDATA-1992] Remove partitionId in CarbonTablePath (14 hours ago) <Jacky Li>

 - [X] Any interfaces changed?
 
 - [X] Any backward compatibility impacted?
 
 - [X] Document update required?

 - [X] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2827/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4073/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3771/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4080/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2834/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3778/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4099/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2855/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2858/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4103/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4106/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2861/

**Comment by jackylk** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2863/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4108/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2865/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4110/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2867/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4112/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4120/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2875/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2878/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4123/

**Comment by ravipesala** [comment]
retest sdv please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3782/

**Comment by ravipesala** [comment]
retest sdv please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3784/

**Comment by ravipesala** [comment]
retest sdv please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3786/

**Comment by ravipesala** [comment]
This PR can be closed. Another same PR https://github.com/apache/carbondata/pull/2043 with sdv fix raised

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
