### PR TITLE
[CARBONDATA-1786] [BugFix] Refactored code to avoid null pointer exception while data loading

### PR DESCRIPTION
**Pull request by geetikagupta16**
Refactored code to add hadoop conf to AbstractDFS file constructor

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1333/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1791/

**Comment by geetikagupta16** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1336/

**Comment by geetikagupta16** [comment]
@ravipesala Please review. This PR will resolve the current NullPointer exception for data loading. SDV test cases are failing due to the same issue.

**Comment by ravipesala** [comment]
@jackylk @QiangCai Please check this PR. It seems PR https://github.com/apache/carbondata/pull/1539 makes lot of SDV test fails. Now current master fails in SDV because of this PR 1539 is merged

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1357/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1811/

**Comment by ravipesala** [comment]
PR 1550 fixed it, please close it.

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1817/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1367/

**Comment by chenliang613** [comment]
@geetikagupta16   thanks for your contribution, pr1550 already fixed this issue and merged, please close this PR.

**Pull request closed without merging**
