### PR TITLE
[WIP]SI fix for not equal to filter

### PR DESCRIPTION
**Pull request by vikramahuja1001**
### Why is this PR needed?
 
 
 ### What changes were proposed in this PR?

    
 ### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2019/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3760/

**Comment by ajantha-bhat** [comment]
@vikramahuja1001 : I have handled in my existing open order by limit PR [#3861 ] which can cause this issue using a flag. I think you can check and close this.

**Comment by vikramahuja1001** [comment]
@ajantha-bhat ,i checked that PR, maybe you can add the test cases for not equal and check SI pushdown

**Pull request closed without merging**
