### PR TITLE
[CARBONDATA-583] Add replace function support for spark 1.6 and 2

### PR DESCRIPTION
**Pull request by phalodi**
- Add replace function support with Spark 1.6 and 2.0
- Manually test that replace function is working
- Add replace function example for spark 1.6 and 2.0
- Run all unit test cases

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by nareshpr** [comment]
Can you check regexp_replace spark function? This function replace all substrings of the specified string that matches the pattern

**Comment by phalodi** [comment]
@nareshpr yes regexp_replace function already available in org.apache.spark.sql.functions package so if we want to use that in place of replace then we document it somewhere, Most of time user try replace directly as other database.

**Comment by ravipesala** [comment]
@phalodi  It is not good to add regular udf in carbon module unless carbondata wants it for some other features. What ever the functions available in spark we support the same and user can use the same functions. Carbondata does not require to document about Spark functions, user can refer the documentation of Spark for the same.

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/634/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1265/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3100/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4019/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7166/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5942/

**Pull request closed without merging**
