### PR TITLE
[CARBONDATA-3572] optimize java code checkstyle for LeftCurly rule

### PR DESCRIPTION
**Pull request by lamber-ken**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed? NO
 
 - [x] Any backward compatibility impacted? NO
 
 - [x] Document update required? NO

 - [x] Testing done YES
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.  NO

Checks for the placement of left curly braces ('{') for code blocks, for a bad style example

#### org.apache.carbondata.core.datastore.compression.AbstractCompressor
``` 
@Override
public boolean supportReusableBuffer() {
  return false;
}

@Override
public boolean supportUnsafe() { return false; }
```

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/809/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/813/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/816/

**Comment by jackylk** [comment]
LGTM

**Comment by jackylk** [comment]
Thanks for working on this

**Pull request closed without merging**
