### PR TITLE
[ISSUE-4306] Fix the error of SDKS3SchemaReadExample

### PR DESCRIPTION
**Pull request by xubo245**
Fix the issue when read schema from S3

 ### Why is this PR needed?
 There are some error when I run the SDKS3SchemaReadExample 
https://github.com/apache/carbondata/issues/4306
 
 ### What changes were proposed in this PR?

    Fix the error of SDKS3SchemaReadExample
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No, optimize the example

### CODE REVIEW

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4674/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/766/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6382/

**Comment by chenliang613** [comment]
LGTM

**Pull request merged**
