### PR TITLE
[CARBONDATA-991] test case to validate log file creation at the configured bad store location

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1811/

**Comment by mohammadshahidkhan** [comment]
PR builder passed:
@http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1818/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1965/

**Comment by mohammadshahidkhan** [comment]
retest this please

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/93/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2221/

**Comment by mohammadshahidkhan** [comment]
raised duplicate pr https://github.com/apache/carbondata/pull/1012

**Pull request closed without merging**
