### PR TITLE
Reverted spark 2.1 to 1.6 as build-all profile cannot work.

### PR DESCRIPTION
**Pull request by ravipesala**

### CODE REVIEW

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/347/

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/357/

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/361/

**Pull request closed without merging**
