### PR TITLE
[CARBONDATA-1265] Fix AllDictionary because it is only supported when single_pass is true

### PR DESCRIPTION
**Pull request by chenerlu**
Fix AllDictionary because it is only supported when single_pass is true

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2898/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/311/

**Comment by chenerlu** [comment]
Have merged.

**Pull request closed without merging**
