### PR TITLE
[CARBONDATA-1884] SDV test cases for CTAS support to carbondata

### PR DESCRIPTION
**Pull request by pawanmalwal**
SDV test cases for CTAS support to carbondata.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [X] Any interfaces changed?
 None

 - [X] Any backward compatibility impacted?
 NA

 - [X] Document update required?
NA

 - [X] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
 Added SDV test cases for CTAS support to carbondata

 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by ravipesala** [comment]
retest sdv please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2503/

**Comment by pawanmalwal** [comment]
retest sdv please

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2509/

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
