### PR TITLE
[HOTFIX]Revert wrong pom changes commit during prepare release process.

### PR DESCRIPTION
**Pull request by akashrn5**
### Why is this PR needed?
 Due to wrong branch release, wrong pom changes are present.
 
 ### What changes were proposed in this PR?
revert the pom changes.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by kunal642** [comment]
LGTM.. only pom change revert so no need to wait for CI.

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5650/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/3907/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/54/

**Pull request closed without merging**
