### PR TITLE
[CARBONDATA-921] resolved bug for unable to select outoforder columns in hive

### PR DESCRIPTION
**Pull request by anubhav100**
trying to select columns which are out of order always result in class cast exception

- added functionality for reading columns which are out of order in hive`
- tested manually with hive cli 
-added example for selecting columns out of order in hive in hive example

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1707/

**Comment by anubhav100** [comment]
@chenliang613 can you have a look?

**Comment by cenyuhai** [comment]
LGTM @QiangCai  @chenliang613

**Comment by anubhav100** [comment]
@chenliang613 @cenyuhai  can it be merged now there are some other prs dependent on this pr

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2087/

**Comment by QiangCai** [comment]
@anubhav100 please push empty commit to run jinkens CI  again.

**Comment by anubhav100** [comment]
@QiangCai i pushed the empty commit

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2092/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2093/

**Comment by QiangCai** [comment]
@chenliang613  looks good, suggest to merge to hive branch

**Comment by chenliang613** [comment]
retest this please

**Comment by anubhav100** [comment]
@chenliang613 its working fine in my pc ,on ci it is showing table is locked for deletion

**Comment by chenliang613** [comment]
retest this please

**Comment by anubhav100** [comment]
why it is failing its working fine on my machine i have build success

**Comment by chenliang613** [comment]
@anubhav100  this pr has been merged , can you manually close this PR.

**Comment by anubhav100** [comment]
@chenliang613 sure thanks closing this pr

**Pull request closed without merging**
