### PR TITLE
[CARBONDATA-698]resolved bug for no_inverted_index

### PR DESCRIPTION
**Pull request by anubhav100**
CARBONDATA-698
 i am creating no_inverted_index with invalid values using both spark 1.6 and 2.1 and it works
spark 2.1 logs

0: jdbc:hive2://localhost:10000> DROP TABLE IF EXISTS  productSalesTable;
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (3.621 seconds)
0: jdbc:hive2://localhost:10000>   CREATE TABLE productSalesTable( productNumber Int, productName String, storeCity String, storeProvince String, productCategory String, productBatch String, saleQuantity Int, revenue Int) STORED BY 'carbondata' TBLPROPERTIES ('COLUMN_GROUPS'='( productName)','DICTIONARY_INCLUDE'='productName', 'NO_INVERTED_INDEX'='1');

spark 1.6 logs

cc.sql("DROP TABLE IF EXISTS  productSalesTable").show();

    cc.sql("""CREATE TABLE productSalesTable( productNumber Int, productName String, storeCity String, storeProvince String, productCategory String, productBatch String, saleQuantity Int, revenue Int) STORED BY 'carbondata' TBLPROPERTIES ('COLUMN_GROUPS'='( productName)','DICTIONARY_INCLUDE'='productName', 'NO_INVERTED_INDEX'='1')""").show()

AUDIT 07-02 15:48:14,485 - [knoldus][knoldus][Thread-1]Creating Table with Database name [default] and Table name [productsalestable]
AUDIT 07-02 15:48:14,868 - [knoldus][knoldus][Thread-1]Table created with Database name [default] and Table name [productsalestable]

while debugging the code i found out in carbon ddl sql parser tablePropertiess map contain the properties in lower case
and we are checking tableProperties.get("NO_INVERTED_INDEX")

so it is failing due to string mismatch

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/841/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/844/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/869/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/870/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/871/

**Comment by Zhangshunyu** [comment]
Hi, except this problem, there is another problem that inverted index info is not stored into thrift info, and when restart cluster, this  info would lost. Could you pls check this pr?
https://github.com/apache/incubator-carbondata/pull/222

**Comment by ravipesala** [comment]
Yes @Zhangshunyu , Can you reopen that PR https://github.com/apache/incubator-carbondata/pull/222 and rebase it, we can merge it now.

**Comment by ravipesala** [comment]
Please close it, it is already handled it.

**Pull request closed without merging**
