### PR TITLE
[CARBONDATA-1677]  [BugFix] Resolved bug for presto not showing table not found exception when table is dropped from carbon  

### PR DESCRIPTION
**Pull request by anubhav100**
**Steps to reproduce** : same as https://issues.apache.org/jira/browse/CARBONDATA-1677

Resolved bug for presto not showing table not found exception when table is dropped from carbon 
 
**Reason**: because table key still exists in presto carboncache it should be removed when the table with that key is dropped from carbon using thrift server

**How To Verify This Pr**: Same As https://issues.apache.org/jira/browse/CARBONDATA-1677

**Testing Is Done Manually**:

1.**In Carbon**

0: jdbc:hive2://localhost:10000> create table carbontable(id int) stored by 'carbondata';
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.121 seconds)
0: jdbc:hive2://localhost:10000> insert into carbontable values(1);
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.21 seconds)

: jdbc:hive2://localhost:10000> drop table carbontable;
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.12 seconds)

2. **Inside Presto Cli**

presto:default> select * from carbontable;
Query 20171110_134429_00007_kb7jx failed: Table 'default.carbontable' not found

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/885/

**Comment by anubhav100** [comment]
@chenliang

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1500/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/930/

**Comment by anubhav100** [comment]
Retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/935/

**Comment by anubhav100** [comment]
@chenliang can you please review this pr?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/938/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1545/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1550/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1553/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/970/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/971/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/980/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1584/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1585/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1590/

**Comment by chenliang613** [comment]
@anubhav100  this pr is same as 1486 ?

**Comment by anubhav100** [comment]
@chenliang613 my pr 1486 has resolved both the issues CARBONDATA-1694,CARBONDATA-1677 I cut my branch CARBONDATA-1694 from this 
branch to make sure that if this pr get merged first then there is no merge conflict.now both issue  CARBONDATA-1694,CARBONDATA-1677 are resolved because my pr 1486 is merged on master i am closing this pr and marking the jira issues as resolved

thanks a lot

**Pull request closed without merging**
