### PR TITLE
[CARBONDATA-3656] set Default TaskNo To Avoid Conflicts when concurrently write data by SDK

### PR DESCRIPTION
**Pull request by xubo245**
### Why is this PR needed?
 Fix Conflicts when concurrently write data by SDK and didn't set taskNo
 
 ### What changes were proposed in this PR?
  set Default TaskNo  when TaskNo is null
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1538/

**Comment by marchpure** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1548/

**Comment by Zhangshunyu** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1564/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1591/

**Comment by xubo245** [comment]
CI pass

**Comment by Zhangshunyu** [comment]
LGTM

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1596/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
