### PR TITLE
[CARBONDATA-1236] Support absolute path without scheme in loading

### PR DESCRIPTION
**Pull request by dhatchayani**
While giving the raw data in LOAD command, the path should be with the scheme like hdfs:// , viewfs:// etc. with this improvement the data path can be absolute path without the scheme. data path for load data and pre-created dictionary data are improved here.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2732/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/157/

**Comment by dhatchayani** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/660/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/660/org.apache.carbondata$carbondata-core/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core</a>: <span class='status-failure'>3</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/660/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.util/CarbonUtilTest/testToCheckAndAppendHDFSUrlWithBlackSlash/'><strong>org.apache.carbondata.core.util.CarbonUtilTest.testToCheckAndAppendHDFSUrlWithBlackSlash</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/660/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.util/CarbonUtilTest/testToCheckAndAppendHDFSUrlWithNull/'><strong>org.apache.carbondata.core.util.CarbonUtilTest.testToCheckAndAppendHDFSUrlWithNull</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/660/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.util/CarbonUtilTest/testToCheckAndAppendHDFSUrlWithNoBlackSlash/'><strong>org.apache.carbondata.core.util.CarbonUtilTest.testToCheckAndAppendHDFSUrlWithNoBlackSlash</strong></a></li></ul>

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2734/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/159/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/662/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2735/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/663/

**Comment by gvramana** [comment]
LGTM

**Pull request closed without merging**
