### PR TITLE
[CARBONDATA-1267] Add short_int case branch in deltaIntegerCodec

### PR DESCRIPTION
**Pull request by xuchuanyin**
I've tested in my environment.The problem is resolved and the query is OK.

# BRIEF

when encoding column value by DeltaIntegerCodec, SHORT_INT may be a target type, but this value doesnot exist in swith-case branch, so exception will be thrown in some case.

# ANALYZE：

This error occurs in particular situation. In my case, there is a measure column called` BEGIN_TIME` and its datatype is `LONG`. When encoding this measure, carbondata use the statistic information `(min: 1497376581, max: 1497423838, decimal: 0 )` and finally decide to use `DeltaIntegerCodec` encoder with source datatype `LONG` and target datatype `SHORT_INT(a internal datatype using three bytes)`. But the encode method in `DeltaIntegerCodec` does not consider this situation, so exception will be thrown.

# ERROR

Detail error message is shown below:
java.lang.RuntimeException: internal error: org.apache.carbondata.core.datastore.page.encoding.DeltaIntegerCodec[src type: LONG, target type: SHORT_INT, stats(min: 1497376581, max: 1497423838, decimal: 0 )]
	at org.apache.carbondata.core.datastore.page.encoding.DeltaIntegerCodec$1.encode(DeltaIntegerCodec.java:147)
	at org.apache.carbondata.core.datastore.page.SafeFixLengthColumnPage.encode(SafeFixLengthColumnPage.java:324)
	at org.apache.carbondata.core.datastore.page.encoding.DeltaIntegerCodec.encode(DeltaIntegerCodec.java:71)
	at org.apache.carbondata.processing.store.TablePageEncoder.encodeAndCompressMeasures(TablePageEncoder.java:75)
	at org.apache.carbondata.processing.store.TablePageEncoder.encode(TablePageEncoder.java:64)
	at org.apache.carbondata.processing.store.CarbonFactDataHandlerColumnar.processDataRows(CarbonFactDataHandlerColumnar.java:364)
	at org.apache.carbondata.processing.store.CarbonFactDataHandlerColumnar.access$500(CarbonFactDataHandlerColumnar.java:65)
	at org.apache.carbondata.processing.store.CarbonFactDataHandlerColumnar$Producer.call(CarbonFactDataHandlerColumnar.java:749)
	at org.apache.carbondata.processing.store.CarbonFactDataHandlerColumnar$Producer.call(CarbonFactDataHandlerColumnar.java:726)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2914/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/328/

**Comment by jackylk** [comment]
Can you add your query as a testcase?

**Comment by xuchuanyin** [comment]
OK, I'll add the test

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2971/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/383/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2972/

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/384/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2973/

**Comment by xuchuanyin** [comment]
it seems the error has nothing to do with my modification.

retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2981/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/392/

**Comment by xuchuanyin** [comment]
The tests are passed.

Can one of the admins verify this patch?

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
