### PR TITLE
[CARBONDATA-1776] Fix some possible test errors that are related to compaction

### PR DESCRIPTION
**Pull request by xubo245**
Fix some possible test errors that are related to compaction
This PR only changed test class 

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 No
 - [x] Any backward compatibility impacted?
 No
 - [x] Document update required?
No
 - [x] Testing done
only change test class, no new test
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
MR120

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1307/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1309/

**Comment by xubo245** [comment]
Please review it @jackylk

**Comment by jackylk** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1780/

**Pull request closed without merging**
