### PR TITLE
[CARBONDATA-1372]Fix  link error in CarbonData documentation

### PR DESCRIPTION
**Pull request by xubo245**
The  link of "building CarbonData" is error, fix it.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by chenliang613** [comment]
i tested it , the link is working fine.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/189/

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/242/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
