### PR TITLE
[HOTFIX] fix compile error after merging PR-2749

### PR DESCRIPTION
**Pull request by zzcclp**
fix compile error after merging #2749 

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by zzcclp** [comment]
@ajantha-bhat @jackylk please review, thanks.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/493/

**Comment by zzcclp** [comment]
retest this please.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/495/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/8744/

**Comment by ajantha-bhat** [comment]
@zzcclp :  Changes are OK.

Why this problem is not catching in PR builder and local maven build ? How to find this type of problems ?

**Comment by zzcclp** [comment]
@ajantha-bhat , I found this issue in my Eclipse project, currently the test cases of 'CarbonCliTest' doesn't run in CI, right?  @jackylk @chenliang613

**Comment by ajantha-bhat** [comment]
@zzcclp : Also I don't think fixing just this compilation error is enough, because still this module has find-bugs issues also.
Example: at DataSummary.java:[line 138] ICAST_IDIV_CAST_TO_DOUBLE

Better to fix everything and check whether can we add this cli-tool module to PR builder profile? 
because future code change from someone again can cause the same problems. 
PR builder should catch this.

@jackylk , @ravipesala : Any suggestions ?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/8760/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/693/

**Pull request closed without merging**
