### PR TITLE
[CARBONDATA-1627] one job failed among 100 job while performing selec…

### PR DESCRIPTION
**Pull request by kushalsaha**
…t operation with 100 different thread

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
NO
 
 - [ ] Any backward compatibility impacted?
 NO
 - [ ] Document update required?
No
 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
=> this issue is resolved when we launch 100 job through jmeter and one job was getting failed because multiple thread would try to initialize the variable even tough the call is made through lazy, but still in multiple thread cases multiple thread tried to initialize variable, to avoid this added synchronized block so that only one thread only can initialize the variable and latter for other thread there's no chance of accessing that block.
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
No large changes

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/829/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1463/

**Comment by ravipesala** [comment]
@kushalsaha please rebase the code

**Comment by ravipesala** [comment]
@kushalsaha Please squash to single commit, I cannot rebase our PR

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1575/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/998/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1615/

**Comment by ravipesala** [comment]
@kushalsaha please rebase the code

**Comment by kushalsaha** [comment]
@ravipesala conflicts resolved please merge

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1104/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1705/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
