### PR TITLE
[CARBONDATA-1270] Documentation update for Delete by ID and DATE syntax and example

### PR DESCRIPTION
**Pull request by sgururajshetty**
Syntax and example updated for 
Delete by ID an DATE

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
