### PR TITLE
[CARBONDATA-1553][Spark2.2]Add two packages for integrating spark2.2 and pom files

### PR DESCRIPTION
**Pull request by zzcclp**
1. Add new package spark2.2 and pom file in carbon/integration
2. Add new package examples-spark2.2 and pom file in carbon/examples

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/739/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1376/

**Comment by zzcclp** [comment]
@chenliang613 @jackylk @sounakr @ravipesala please take a look , thanks

**Comment by chenliang613** [comment]
This Jira ticket(CARBONDATA-1553) may not require.   spark2.1 and spark2.2 integration code can together put to integration/spark2, because there are on big changes.

**Comment by zzcclp** [comment]
OK, I close this.

**Comment by sounakr** [comment]
@zzcclp I agree with @chenliang613. We will places all the Spark2.2 related changes inside spark2 as it is a minor version release. For major releases we can make a new directory inside integration.

**Comment by zzcclp** [comment]
@sounakr OK, I got it.

**Pull request closed without merging**
