### PR TITLE
[CARBONDATA-1219] Documentation - not supported high.cardinality.row.count.percentage

### PR DESCRIPTION
**Pull request by srigopalmohanty**
The parameter high.cardinality.row.count.percentage should be removed and all the reference also needs to be removed.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/483/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3072/

**Comment by chenliang613** [comment]
@sgururajshetty  please review it

**Comment by sgururajshetty** [comment]
LGTM

**Comment by sgururajshetty** [comment]
@chenliang613 please review and merge

**Pull request closed without merging**
