### PR TITLE
[HotFix][CheckStyle] Fix import related checkstyle

### PR DESCRIPTION
**Pull request by xuchuanyin**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 `NO`
 - [x] Any backward compatibility impacted?
  `NO`
 - [x] Document update required?
 `NO`
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
 `NO, only checkstyle fixed`
        - How it is tested? Please attach test report.
 `NO, only checkstyle fixed`
        - Is it a performance related change? Please attach the performance test report.
 `NO, only checkstyle fixed`
        - Any additional information to help reviewers in testing this change.
 `NO, only checkstyle fixed`
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
 `NO, only checkstyle fixed`

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3580/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2342/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3430/

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3592/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/2354/

**Comment by jackylk** [comment]
LGTM

**Comment by jackylk** [comment]
merged into carbonstore branch

**Pull request closed without merging**
