### PR TITLE
[WIP][CARBONDATA-2068][CARBONDATA-1516][Tests] Drop datamap should work for timeseries preaggregate table

### PR DESCRIPTION
**Pull request by xubo245**
- [ ] Any interfaces changed?
      No
 - [ ] Any backward compatibility impacted?
    No
 - [ ] Document update required?
No
 - [ ] Testing done
        add test case for drop timeseries pre aggregate table
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
No

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3058/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3061/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1829/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3050/

**Comment by xubo245** [comment]
sql(s"drop datamap if exists agg1 on table mainTable")  not support,
 Carbon support    sql(s"drop datamap if exists agg1_year on table mainTable").

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3052/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1853/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/3084/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3070/

**Pull request closed without merging**
