### PR TITLE
[CARBONDATA-2608] Document update about Json Writer with examples.

### PR DESCRIPTION
**Pull request by ajantha-bhat**
[CARBONDATA-2608] Document update about Json Writer with examples.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?NA
 
 - [ ] Any backward compatibility impacted?NA
 
 - [ ] Document update required?yes, updated

 - [ ] Testing done. NA
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6544/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5373/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5448/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
