### PR TITLE
[CARBONDATA-1254] Fixed describe formatted for sort columns after alter

### PR DESCRIPTION
**Pull request by BJangir**
Analysis: Earlier if we delete any column still it was being listed in describe formatted.

Solution: Filtering deleted columns from sort columns list

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2830/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/250/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2831/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/251/

**Comment by kumarvishal09** [comment]
retest this please

**Comment by kumarvishal09** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/296/

**Comment by BJangir** [comment]
Merged to master so closing the same.

**Pull request closed without merging**
