### PR TITLE
[CARBONDATA-3791]: Query and Compaction changes in configuration parameters

### PR DESCRIPTION
**Pull request by vikramahuja1001**
### Why is this PR needed?
 Query and Compaction changes in configuration parameters as per the code.
 
 ### What changes were proposed in this PR?
Query and Compaction changes in configuration parameters as per the code.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1213/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2931/

**Comment by VenuReddy2103** [comment]
LGTM

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2963/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1245/

**Pull request closed without merging**
