### PR TITLE
[HOTFIX]Upgrade pom version from 1.3.0 to 1.4.0 in processing/pom.xml

### PR DESCRIPTION
**Pull request by gangken**
See #1961

### CODE REVIEW

**Comment by gangken** [comment]
Hi, @chenliang613 , PTAL.

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
@gangken  yes, you are right, pr 1961 missed change this pom version.  Thanks for your contribution. but pr #1955 already fixed it.

**Comment by gangken** [comment]
ACK

**Comment by chenliang613** [comment]
Again, thanks for your contribution.  Can you please close this PR, look forward to seeing your other PRs.

**Pull request closed without merging**
