### PR TITLE
[CARBONDATA-4269] Update url and description in prestosql-guide.md

### PR DESCRIPTION
**Pull request by czy006**
[CARBONDATA-4269] Update url and description in prestosql-guide.md

## Why is this PR needed?

PrestoSQL has now changed its name to Trino. Because Facebook established the Presto Foundation at The Linux Foundation®，Led to prestosql Must be change the name
More information can see here

## What changes were proposed in this PR?

https://prestosql.io/docs/current/installation/deployment.html
at now is Jump to the prestodb Instead of jumping to prestosql（trino),we must fix it and tell user prestosql website is migration to the trino

## Does this PR introduce any user interface change?

No
## Is any new testcase added?

No

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/241/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4093/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5837/

**Comment by chenliang613** [comment]
LGTM

**Comment by chenliang613** [comment]
@czy006  please fix the confict.

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4108/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/5852/

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/256/

**Pull request closed without merging**
