### PR TITLE
[CARBONDATA-3723] Fix insert failure when partition column is a first column of projection in MV

### PR DESCRIPTION
**Pull request by ajantha-bhat**
### Why is this PR needed?
 For Alter table drop and add column scenarios, partition columns may not be in the end of create-order column. So, added a logic to keep the partition column in the end in #3634.

But partition may not be the last projection column during mv creation. So now, create order partition is kept last, but the projection is not last. Hence the insert gives wrong data or fails.
 
 ### What changes were proposed in this PR?
rearrage partition to last in create order columns, only for alter table scenarios

TODO: analyze and handle Alter table schema + MV
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/485/

**Comment by jackylk** [comment]
LGTM

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2185/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
