### PR TITLE
[CARBONDATA-1122] SessionState hiveclient to be used for all the sql's run on hive metastore

### PR DESCRIPTION
**Pull request by nareshpr**
Changed code to use hiveClient available in HiveSessionState. This handler is user specific hive client.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2201/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/68/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
