### PR TITLE
[CARBONDATA-1442] Refactored Partition-Guide.md

### PR DESCRIPTION
**Pull request by jatin9896**
Refactored the partition-guide.md file to maintain consistency of headings across the all the doc files and formatted the syntax to generate correct pdf for the carbondata website.

### CODE REVIEW

**Comment by PallaviSingh1992** [comment]
@sgururajshetty @chenliang613 please review this

**Comment by Ayushi93** [comment]
LGTM
@chenliang613 kindly review

**Comment by sgururajshetty** [comment]
LGTM
@chenliang613  kindly review

**Comment by jackylk** [comment]
It seems this PR contains some commit from master. Can you rebase and squash your commit? @jatin9896

**Comment by Ayushi93** [comment]
I shall be doing it today by EOD.

On 06-Sep-2017 7:33 PM, "Jacky Li" <notifications@github.com> wrote:

It seems this PR contains some commit from master. Can you rebase and
squash your commit? @jatin9896 <https://github.com/jatin9896>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/apache/carbondata/pull/1310#issuecomment-327493321>,
or mute
the thread

**Comment by PallaviSingh1992** [comment]
@jackylk I have squashed the commits

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/587/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
