### PR TITLE
[CARBONDATA-3406] Support Binary, Boolean,Varchar, Complex data types read and Dictionary columns read

### PR DESCRIPTION
**Pull request by dhatchayani**
(1) Support Read for Binary, Boolean, Varchar, Complex data types.
(2) Support Read for Dictionary columns.

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [x] Testing done
        Manual Testing
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3407/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11674/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3610/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
