### PR TITLE
[CARBONDATA-1309] During Global Sort the DataWriterProcessorStepImpl not getting shutdown even when datalaod is finished.

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
Global Sort is not closing the DataWriterProcessorStepImpl because of this the thread started to print the number of records processed by the step at the interval of 10 second is not getting shutdown.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3150/

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
