### PR TITLE
[Documentation] Example added for Drop Partition

### PR DESCRIPTION
**Pull request by sgururajshetty**
Example added for Drop Partition

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3899/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3144/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4376/

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
