### PR TITLE
[CARBONDATA-1652] Add examples for Carbon usage when integrating with Spark

### PR DESCRIPTION
**Pull request by jackylk**
It is good to have more examples for user reference. 
This PR adds back examples from spark-example module in earlier spark 1 integration

 - [X] Make sure the PR title is formatted like:
   `[CARBONDATA-<Jira issue #>] Description of pull request`
   
 - [X] Make sure to add PR description

 - [X] Any interfaces changed?
   None

 - [X] Any backward compatibility impacted?
   None

 - [x] Document update required?
   None

 - [X] Testing done
  Yes
  No new testcase is added
         
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
                 
---

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/704/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1340/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/710/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1346/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/719/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1356/

**Pull request closed without merging**
