### PR TITLE
[CARBONDATA-3774]Fix hiding the actual exceptions during tableExists check

### PR DESCRIPTION
**Pull request by akashrn5**
### Why is this PR needed?
 1. In table exists API, we catch all exceptions and say table does not exists which is wrong

 ### What changes were proposed in this PR?
1. Catch only NoSuchTableException fro spark and return false, for other exceptions, throw it to caller

    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No(existing test will take care)

### CODE REVIEW

**Comment by akashrn5** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1046/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2759/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2760/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1047/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
