### PR TITLE
[CARBONDATA-1227] Remove useless TableCreator

### PR DESCRIPTION
**Pull request by chenerlu**
Just remove useless TableCreator because nobody will call it.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/127/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2701/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/626/

**Comment by QiangCai** [comment]
LGTM

**Pull request merged**
