### PR TITLE
[HOTFIX] [presto] presto integration code cleanup

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Changes in the PR:
a. Removed spark jars from release jars dependency
b. enable check style for presto module
c. fixed all the checkstyle for presto module

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed? NA
 
 - [ ] Any backward compatibility impacted? NA
 
 - [ ] Document update required? NA

 - [ ] Testing done. NA
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.  NA

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/6202/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7828/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/6552/

**Comment by ajantha-bhat** [comment]
@chenliang613 : please review.

**Comment by ajantha-bhat** [comment]
@bhavya411 : please review

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
