### PR TITLE
[WIP][CARBONDATA-2532][Integration] Carbon to support spark 2.3 version

### PR DESCRIPTION
**Pull request by sandeep-katta**
**What changes were proposed in this pull request?**

1.In general carbon is need to correct the API changes done by the spark in 2.3.0
2.Added 1 more folder in integration/spark2 for 2.3 support
3.New profile is added for spark 2.3

**How was this patch tested?**
Existing testcases.
Some issues are pending will be correcting meanwhile

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by sandeep-katta** [comment]
Duplicate of [WIP][CARBONDATA-2532][Integration] Carbon to support spark 2.3 version

**Pull request closed without merging**
