### PR TITLE
[ISSUE-4305] Optimize the magic number

### PR DESCRIPTION
**Pull request by xubo245**
### Why is this PR needed?
 There are some code style， which should be optimized
 
 ### What changes were proposed in this PR?
optimize the magic code in example 
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No, only change the example

### CODE REVIEW

**Comment by chenliang613** [comment]
LGTM

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6379/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4671/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/762/

**Pull request merged**
