### PR TITLE
[CARBONDATA-929] adding optional field number of blocklet in the carbonindex file

### PR DESCRIPTION
**Pull request by mohammadshahidkhan**
The num_blocklet needed to get the number of Blocklet within a block at the driver

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1631/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1632/

**Comment by mohammadshahidkhan** [comment]
@ravipesala this requires building with format

**Comment by mohammadshahidkhan** [comment]
Manual PR builder pass for spark2.1 is passed.
http://136.243.101.176:8080/job/ManualApacheCarbonPRBuilder2.1/115/

**Comment by mohammadshahidkhan** [comment]
Manual build for spark 1.5 is passed
http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1656/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 1.6.2, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/1819/

**Comment by mohammadshahidkhan** [comment]
This PR contains changes in thrift file, please some one do the need full thing.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/191/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2338/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/215/

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/81/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1251/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/620/

**Comment by mohammadshahidkhan** [comment]
Not required for current design.
Please reopen if required in future.

**Pull request closed without merging**
