### PR TITLE
[HOTFIX] Changes to align printing of information in explain command based on enable.query.statistics flag

### PR DESCRIPTION
**Pull request by manishgupta88**
Now user need to set the flag enable.query.statistics = true to print the pruning and dataMap related information in the explain command.

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/683/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/8946/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/878/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
