### PR TITLE
[CARBONDATA-3206] Fix some spell error in CarbonData

### PR DESCRIPTION
**Pull request by WangQingNa**
numberofColumnPerIO => numberOfColumnPerIO
iexpectedMinSizePerNode => expectedMinSizePerNodeInt
parentname => parentName
nullformat => nullFormat

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 
org.apache.carbondata.processing.datatypes.ArrayDataType
org.apache.carbondata.processing.datatypes.PrimitiveDataType
org.apache.carbondata.core.scan.complextypes.StructQueryType
org.apache.carbondata.core.scan.complextypes.ComplexQueryType
org.apache.carbondata.core.scan.complextypes.ArrayQueryType
org.apache.carbondata.core.scan.filter.GenericQueryType
parentname => parentName

 - [x] Any backward compatibility impacted?
    No
 - [x] Document update required?
    No
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
          No
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
    No

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2100/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10354/

**Comment by xubo245** [comment]
@WangQingNa  
1. Please optimize this title， for example: [CARBONDATA-3206] Fix some spell errors in CarbonData.
2. Please finish the checklist
3.Please fix the CI errors.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10356/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2307/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2102/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2103/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10357/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2308/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2104/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2309/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10358/

**Comment by xubo245** [comment]
LGTM. Thanks you for your contribution.

**Comment by xubo245** [comment]
Some review comments in https://github.com/apache/carbondata/pull/3040

**Pull request closed without merging**
