### PR TITLE
[WIP]added compression and range column based FT for SI

### PR DESCRIPTION
**Pull request by nihal0107**
### Why is this PR needed?
 
 
 ### What changes were proposed in this PR?

    
 ### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA2** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/3172/

**Comment by CarbonDataQA2** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4926/

**Comment by ajantha-bhat** [comment]
@nihal0107 : I think all the SI related testcases you can add in your existing #4023 itself.

**Comment by nihal0107** [comment]
Added in #4023

**Pull request closed without merging**
