### PR TITLE
[CARBONDATA-3007][Doc] Fix error in documents

### PR DESCRIPTION
**Pull request by xuchuanyin**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 `NO`
 - [x] Any backward compatibility impacted?
  `NO`
 - [x] Document update required?
 `YES`
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
 `NA`
        - How it is tested? Please attach test report.
 `NA`
        - Is it a performance related change? Please attach the performance test report.
 `NA`
        - Any additional information to help reviewers in testing this change.
        `NA`
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
 `NA`

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/791/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9056/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/988/

**Comment by xuchuanyin** [comment]
@sraghunandan please review this PR

**Pull request closed without merging**
