### PR TITLE
[CARBONDATA-1441]resolved the bug for schema not reflect back in hive

### PR DESCRIPTION
**Pull request by anubhav100**
https://issues.apache.org/jira/browse/CARBONDATA-1441

when you alter table in carbondata that schema is not reflect back in hive

### CODE REVIEW

**Comment by anubhav100** [comment]
@cenyuhai @chenliang613

**Comment by cenyuhai** [comment]
It looks good, I will test it on my computer

**Comment by anubhav100** [comment]
retest this please

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
