### PR TITLE
Only for test ci(vacuous PR-don't merge)

### PR DESCRIPTION
**Pull request by chenliang613**
Only for test ci(vacuous PR-don't merge)

### CODE REVIEW

**Comment by chenliang613** [comment]
ok

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
ok to test

**Comment by chenliang613** [comment]
ok to test

**Comment by chenliang613** [comment]
ok to test

**Comment by chenliang613** [comment]
any message

**Comment by chenliang613** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by chenliang613** [comment]
test

**Comment by chenliang613** [comment]
ok to test

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2124/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2125/

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2142/

**Comment by chenliang613** [comment]
text

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2157/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-2.1/51/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/22/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2192/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/59/

**Pull request closed without merging**
