### PR TITLE
[CARBONDATA-1251] Add test cases for IUD feature

### PR DESCRIPTION
**Pull request by chenerlu**
Just add test cases for IUD feature.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2821/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/241/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
