### PR TITLE
[HOTFIX] Fix dataloading/insertInto complex data type issue for partition table

### PR DESCRIPTION
**Pull request by QiangCai**
### Why is this PR needed?
 Both dataLoading and insertInto with complex data type are not working fine
 
 ### What changes were proposed in this PR?
for the partition table, the complex data type of target table should be converted to the binary data type.
    
 ### Does this PR introduce any user interface change?
 No

 ### Is any new testcase added?
Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/1393/

**Comment by CarbonDataQA1** [comment]
Build Failed with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/1403/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1415/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
