### PR TITLE
[CARBONDATA-1702] [Segment-Reading] added doc for "query from specified segments" feature 

### PR DESCRIPTION
**Pull request by praveenmeenakshi56**
Documentation of segment reading

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [X] Any interfaces changed? No
 
 - [X] Any backward compatibility impacted? No
 
 - [X] Document update required? NA

 - [X] Testing done NA 
       
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
@praveenmeenakshi56 please follow the same structure like ALTER TABLE 

Heading
    Description
    Syntax
    Properties (if any)
    Example

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
