### PR TITLE
[CARBONDATA-1307] Fix bug for TableInfo serialization problem in cluster mode

### PR DESCRIPTION
**Pull request by jackylk**
TableInfo serialization has problem when there are scala list in ColumnSchema, this PR fixed this issue

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/491/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3080/

**Comment by ravipesala** [comment]
@jackylk There is one testcase is failing, please fix it

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3086/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/496/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
