### PR TITLE
[CARBONDATA-3793]Fix update and delete issue when multiple partition columns are present and clean files issue

### PR DESCRIPTION
**Pull request by akashrn5**
### Why is this PR needed?
1. After #3837 , when there are multiple partition columns are present in table, update and delete not happening as , it was considering the tuple id as external segment tuple ID , Because when multiple partitions are present TID contains # character. 
2. when multiple segments are present, and some segments are updated, and clean files delete the segment files of non updated segments considering as stale files.
 
 ### What changes were proposed in this PR?
1. To double check for external segment, check if the segment metadata details  has path is not null.
2. delete the old segment files of only the updated segments.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
  - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2232/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3972/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3981/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2241/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/3982/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2242/

**Comment by akashrn5** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2283/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4021/

**Comment by akashrn5** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4040/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2301/

**Comment by akashrn5** [comment]
@kunal642 build passed, please help to review.

**Comment by kunal642** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4056/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2318/

**Comment by akashrn5** [comment]
@kunal642 build passed, please check

**Comment by kunal642** [comment]
LGTM

**Comment by akashrn5** [comment]
Jira of this PR is CARBONDATA-3973

**Pull request closed without merging**
