### PR TITLE
[CARBONDATA-2320][Datamap] Fix error in luncene coarse grain datamap suite

### PR DESCRIPTION
**Pull request by xuchuanyin**
add DM-properties while creating datamap, otherwise the test will fail

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 `NO`
 - [x] Any backward compatibility impacted?
  `NO`
 - [x] Document update required?
 `NO`
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
 `NO, only fixed test error`
        - How it is tested? Please attach test report.
`Tested in local`
        - Is it a performance related change? Please attach the performance test report.
`NO`
        - Any additional information to help reviewers in testing this change.
       `NO` 
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
`Not related`

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4325/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4856/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3634/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
