### PR TITLE
[CARBONDATA-1822] Documentation - Added REFRESH TABLE

### PR DESCRIPTION
**Pull request by Indhumathi27**
- [ Yes ] Document updated

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by manishgupta88** [comment]
LGTM

**Pull request closed without merging**
