### PR TITLE
fix timestamp format issue for range partitioned table

### PR DESCRIPTION
**Pull request by QiangCai**
the format of Timestamp/Date use a static variable, it is not proper.

the format of Timestamp/Date:
during dataloading,  if load sql specific datefromat, use it. if not, use carbon property.

during query, use spark/hive dateformat.

during create table, use carbon property.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2519/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/404/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2520/

**Comment by gvramana** [comment]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/405/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/405/org.apache.carbondata$carbondata-core/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/405/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.writer/CarbonFooterWriterTest/testWriteFactMetadata/'><strong>org.apache.carbondata.core.writer.CarbonFooterWriterTest.testWriteFactMetadata</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/405/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.writer/CarbonFooterWriterTest/testReadFactMetadata/'><strong>org.apache.carbondata.core.writer.CarbonFooterWriterTest.testReadFactMetadata</strong></a></li></ul>

**Pull request closed without merging**
