### PR TITLE
[CARBONDATA-917] Resolved Bug for Select Count(*) not Working In Hive 

### PR DESCRIPTION
**Pull request by anubhav100**
- Resolved Bug For Select count(*) not working in hive
 - Test manually with hive cli

### CODE REVIEW

**Comment by anubhav100** [comment]
@chenliang613 i rebased all hive branch prs  for master

**Comment by chenliang613** [comment]
@anubhav100  got the below error when verified this pr: 

hive> select * from hive_table_2;
OK
Failed with exception java.io.IOException:java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
Time taken: 0.434 seconds

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/73/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2207/

**Comment by anubhav100** [comment]
@chenliang613 i rebased this pr you can try it again

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/75/

**Comment by anubhav100** [comment]
@chenliang613 i tested t manualy as well can you merged it now here are logs 

INSIDE SPARK SHELL

scala> carbon.sql("create table counttest(name string,nickname string) stored by 'carbondata'")

scala> carbon.sql("""load data inpath 'hdfs://localhost:54310/chartypetest.csv' into table counttest""").show

INSIDE HIVE SHELL

hive> CREATE TABLE CounttestHIVE (name string,nickname string);
OK
Time taken: 1.202 seconds
hive> ALTER TABLE COUNTTESTHIVE SET FILEFORMAT
    > INPUTFORMAT "org.apache.carbondata.hive.MapredCarbonInputFormat"
    > OUTPUTFORMAT "org.apache.carbondata.hive.MapredCarbonOutputFormat"
    > SERDE "org.apache.carbondata.hive.CarbonHiveSerDe";
OK
Time taken: 0.445 seconds
hive> ALTER TABLE COUNTTESTHIVE SET LOCATION 'hdfs://localhost:54310/opt/carbonStore/default/counttest' ;
OK
Time taken: 0.502 seconds
hive> set hive.mapred.supports.subdirectories=true;
hive> set mapreduce.input.fileinputformat.input.dir.recursive=true;
hive> select * from counttest;
OK
Time taken: 0.089 seconds
hive> select * from counttesthive;
OK
ANUBHAV	'ANU'
Time taken: 0.101 seconds, Fetched: 1 row(s)

hive> select count(*) from counttesthive;

MapReduce Jobs Launched: 
Stage-Stage-1:  HDFS Read: 15760 HDFS Write: 0 SUCCESS
Total MapReduce CPU Time Spent: 0 msec
OK
1
Time taken: 1.463 seconds, Fetched: 1 row(s)

**Comment by chenliang613** [comment]
@anubhav100   please change the commit description , " rebased with master ".

**Comment by anubhav100** [comment]
@chenliang613 changed you can check

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2233/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/106/

**Comment by anubhav100** [comment]
@chenliang613 i changed the commit description you can check

**Pull request closed without merging**
