### PR TITLE
[HOTFIX] Fix compile error after merging PR2705

### PR DESCRIPTION
**Pull request by zzcclp**
Fix compile error after merging PR2705

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by zzcclp** [comment]
@ajantha-bhat , please take a look, thanks.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/286/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/8531/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/461/

**Comment by zzcclp** [comment]
retest sdv please

**Comment by jackylk** [comment]
actually now we have disabled SDV test and will find more test resource and re-enable it later

**Comment by ajantha-bhat** [comment]
@zzcclp : LGTM and Thank you.

**Pull request closed without merging**
