### PR TITLE
[CARBONDATA-2750] Updated Documentation for Local Dictionary Support

### PR DESCRIPTION
**Pull request by praveenmeenakshi56**
### What has been added?
Described about increase in memory footprint in local dictionary.
Added to reduce block size when local dictionary is enabled,

 - [x] Any interfaces changed?
NA
 - [x] Any backward compatibility impacted?
NA
 - [x] Document update required?
Document updated.
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
NA
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/6235/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7871/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/6594/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
