### PR TITLE
[CARBONDATA-3692] Support NoneCompression during loading data.

### PR DESCRIPTION
**Pull request by Pickupolddriver**
### Why is this PR needed?
 In some cases, the data need to be uncompressed after loading into Carbondata file.
In the current version, the project does not support loading data without compression.
It could speed up data loading form Flink to OBS by skipping compress and uncompress data.

 
 ### What changes were proposed in this PR?
Provide a new Compressor as NoneCompressor implements the AbstractCompressor which will actually not compress and uncompress anything.
This compressor can be set by calling
CarbonProperties.getInstance().addProperty(CarbonCommonConstants.COMPRESSOR,"none");
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
- Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Can one of the admins verify this patch?

**Comment by jackylk** [comment]
please push to original PR

**Comment by ajantha-bhat** [comment]
add to whitelist

**Comment by ajantha-bhat** [comment]
@Pickupolddriver : push the review comment fixes to #3611 and close this PR

**Pull request closed without merging**
