### PR TITLE
[WIP]Decoding for alias in case of join and subquery	

### PR DESCRIPTION
**Pull request by ashokblend**
Problem: When query has alias and subquery with join, decoder is not able to decode
Analysis: In case of mentioned problem scenario, aliasMap is not getting populated with its correct origin value.
Solution: Need to populate aliasmap with correct attribute

### CODE REVIEW

**Comment by ravipesala** [comment]
Build Failed, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1272/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/641/

**Comment by ashokblend** [comment]
closing it.

**Pull request closed without merging**
