### PR TITLE
[CARBONDATA-1717]Remove spark broadcast for gettting hadoop configurations

### PR DESCRIPTION
**Pull request by akashrn5**
why?
with the new conf set in hadoop conf, after broadcast conf will not get reflected, hence these changes 
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [*] Any interfaces changed?
 NONE
 - [*] Any backward compatibility impacted?
 NONE
 - [*] Document update required?
NONE
 - [*] Testing done
       test cases are not required, SDV will take care
       
 - [*] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NONE

### CODE REVIEW

**Comment by akashrn5** [comment]
@QiangCai please review

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1147/

**Comment by akashrn5** [comment]
@ravipesala @jackylk please review

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1149/

**Comment by QiangCai** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1150/

**Comment by QiangCai** [comment]
please fix CI issue

**Comment by akashrn5** [comment]
retest this please

**Comment by akashrn5** [comment]
retest sdv pleaase

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1173/

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
