### PR TITLE
[CARBONDATA-1392]Fixed bug for fetching the error value of decimal type in presto

### PR DESCRIPTION
**Pull request by steven-qin**
The following is based on TPCH test.
create statement:
            create table lineitem (l_orderkey int ,l_partkey int ,l_suppkey int ,l_linenumber int ,l_quantity decimal(15,2) ,l_extendedprice decimal(15,2) ,l_discount decimal(15,2) ,l_tax decimal(15,2) ,l_returnflag string ,l_linestatus string ,l_shipdate date ,l_commitdate date ,l_receiptdate date ,l_shipinstruct string ,l_shipmode string ,l_comment string ) stored by 'carbondata'

query sql:
         select l_quantity,l_extendedprice,l_discount,l_tax  from lineitem where l_orderkey=15413986 and l_linenumber=7;

The below is correct in spark:
l_quantity |  l_extendedprice | l_discount | l_tax
11.00        |       16549.17       |      0.07     |  0.04

The below is wrong in presto:
l_quantity |  l_extendedprice |  l_discount | l_tax
0.11          |  165.49                |  0.00          | 0.00

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[CARBONDATA-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
 - [ ] Testing done
 
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - What manual testing you have done?
        - Any additional information to help reviewers in testing this change.
         
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
                 
---

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/778/

**Comment by ravipesala** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3376/

**Comment by ravipesala** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/134/

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/808/

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/812/

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/137/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3407/

**Comment by anubhav100** [comment]
@steven-qin this pr has resolved this issue with more optimizations #1257

**Comment by chenliang613** [comment]
@anubhav100 i prefer to using steven-qin's pull request, because steven-qin fix it earlier.

**Comment by chenliang613** [comment]
retest this please

**Comment by anubhav100** [comment]
@chenliang sure he has done a great job

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/202/

**Comment by anubhav100** [comment]
@steven-qin
1.please correct your PR title as per : https://github.com/apache/carbondata/blob/master/docs/How-to-contribute-to-Apache-CarbonData.md
2.there is still problem with decimal type i tried to run this query in both carbon data and presto from your branch and presto  is giving wrong results

in carbon-----

carbon.sql("select l_tax from lineitem where l_tax=0.06").show()
    carbon.stop()

+-----+
|l_tax|
+-----+
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
| 0.06|
+-----+
only showing top 20 rows

when i execute it in presto 

select l_tax from lineitem where l_tax=0.06;

i get no result

**Comment by steven-qin** [comment]
@anubhav100 
The lastest master branch:
create statement: carbon.sql("create table partsupp2 ( ps_partkey int ,ps_suppkey int ,ps_availqty int , ps_supplycost decimal(15,2) ,ps_comment string ) stored by 'carbondata'")
load statement: carbon.sql("LOAD DATA INPATH '/testdata/partsupp2.csv' INTO TABLE partsupp2  OPTIONS('DELIMITER'='\u0001')")

sql: select * from partsupp2;

 ps_partkey | ps_suppkey | ps_availqty | ps_supplycost |                                                                                            ps_comment                               
------------+------------+-------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------
          1 |          2 |        3325 | 7.72          | , even theodolites. regular, final theodolites eat after the carefully pending foxes. furiously regular deposits sleep slyly. carefu
      75001 |          2 |        8893 | 1.80          | . blithely regular platelets sleep fluffily ironic, regular platelets. slyly regular deposits nag. packages are furiously according 
	

in spark-shell:

sql: carbon.sql("select * from partsupp2").show
+----------+----------+-----------+-------------+--------------------+
|ps_partkey|ps_suppkey|ps_availqty|ps_supplycost|          ps_comment|
+----------+----------+-----------+-------------+--------------------+
|         1|         2|       3325|       771.64|, even theodolite...|
|     75001|         2|       8893|       179.82|. blithely regula...|
+----------+----------+-----------+-------------+--------------------+

	
The pr-1236 branch:

git fetch origin pull/1236/head:pr-1236

sql: select * from partsupp2;

ps_partkey | ps_suppkey | ps_availqty | ps_supplycost |                                                                                            ps_comment                               
------------+------------+-------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------
          1 |          2 |        3325 | 771.64        | , even theodolites. regular, final theodolites eat after the carefully pending foxes. furiously regular deposits sleep slyly. carefu
      75001 |          2 |        8893 | 179.82        | . blithely regular platelets sleep fluffily ironic, regular platelets. slyly regular deposits nag. packages are furiously according

**Comment by steven-qin** [comment]
@anubhav100 
There is not carbondata issue No.

**Comment by bhavya411** [comment]
Hi @steven-qin  can you please remove the extra import " import com.google.common.base.Strings;" from CarbondataRecordCursor. I have verified the PR for both LongDecimalType and ShortDecimalType and it is working fine.

**Comment by steven-qin** [comment]
@bhavya411 
I has removed the extra import " import com.google.common.base.Strings;". Please check it again.

**Comment by bhavya411** [comment]
verified

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/212/

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/214/

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/246/

**Comment by chenliang613** [comment]
retest this please

**Comment by bhavya411** [comment]
LGTM

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
