### PR TITLE
[CARBONDATA-1244] polish docs and comments in presto integration

### PR DESCRIPTION
**Pull request by HoneyQuery**
Rewrite README.md of presto integration and add some comments to presto integration.
Make the README easier for starters to play with. Write more comments for the source code of presto integration to make it more readable.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/297/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2881/

**Pull request closed without merging**
