### PR TITLE
[WIP][CARBONDATA-3199]"show datamap" represents preaggregate datamap

### PR DESCRIPTION
**Pull request by qiuchenjian**
[Problem] "show datamap" command doesn't represents preaggregate datamap, it only represents bloom filter datamap

[Solution]PreAggregateDataMapProvider save datamap schema on hdfs or s3, so that CarbonDataMapShowCommand can get all datamap
 

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
saveDataMapSchema

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1942/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2151/

**Comment by qiuchenjian** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10198/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/2154/

**Comment by ravipesala** [comment]
@qiuchenjian currently pre-aggregate datamap is not following the datamap interfaces as it was implemented before datamap framework. That is why not all datamap DDL works with pre-aggregate.  It is better to keep the pre-aggregate datamap untouched in this area until we decide whether to take MV datamap or pre-aggregate datamap.

**Comment by qiuchenjian** [comment]
> @qiuchenjian currently pre-aggregate datamap is not following the datamap interfaces as it was implemented before datamap framework. That is why not all datamap DDL works with pre-aggregate. It is better to keep the pre-aggregate datamap untouched in this area until we decide whether to take MV datamap or pre-aggregate datamap.

@ravipesala  OK, I will close this PR. But "show datamap" can't return preaggregate ,but it's still called datamap,  which is strange.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/10202/

**Pull request closed without merging**
