### PR TITLE
[CARBONDATA-3645] BadRecords are inserted as NULL when column is of complex data type and BAD_RECORDS_ACTION is IGNORE

### PR DESCRIPTION
**Pull request by Indhumathi27**
### Why is this PR needed?
 In case if `BAD_RECORDS_ACTION` is `IGNORE`, Carbon should skip those bad records while loading. But in case of Complex data type, badrecords are inserted as NULL. Here, `badRecordAdded` flag is not set, from second BadRecord found,since message is already added to `columnMessageMap` for first found BadRecord.
 
 ### What changes were proposed in this PR?
Set `badRecordAdded` flag, if badRecord is found.
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/1373/

**Comment by CarbonDataQA1** [comment]
Build Failed with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/1383/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1393/

**Comment by Indhumathi27** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/1398/

**Comment by CarbonDataQA1** [comment]
Build Failed with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/1407/

**Comment by ydvpankaj97** [comment]
retest this please

**Comment by Indhumathi27** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/1418/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/1438/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/1426/

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
