### PR TITLE
[CARBONDATA-1053] supported char Type for hive

### PR DESCRIPTION
**Pull request by anubhav100**
- supported char type for hive
- tested manually with hive cli

### CODE REVIEW

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by chenliang613** [comment]
retest this please

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2206/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/74/

**Comment by anubhav100** [comment]
@chenliang613 i tested it manually here are logs can you merge it
                      INSIDE SPARK SHELL
scala> carbon.sql("create table chartypes(name string,nickname char) stored by 'carbondata'")
scala> carbon.sql("""load data inpath 'hdfs://localhost:54310/chartypetest.csv' into table chartypes""").show
                      INSIDE HIVE SHELL
hive> CREATE TABLE CHARTYPEHIVE (name string,nickname char(10));
OK
Time taken: 1.214 seconds
hive> ALTER TABLE CHARTYPEHIVE SET FILEFORMAT
    > INPUTFORMAT "org.apache.carbondata.hive.MapredCarbonInputFormat"
    > OUTPUTFORMAT "org.apache.carbondata.hive.MapredCarbonOutputFormat"
    > SERDE "org.apache.carbondata.hive.CarbonHiveSerDe";
OK
Time taken: 0.396 seconds
hive> ALTER TABLE CHARTYPEHIVE SET LOCATION 'hdfs://localhost:54310/opt/carbonStore/default/chartypes' ;

hive> set hive.mapred.supports.subdirectories=true;
hive> set mapreduce.input.fileinputformat.input.dir.recursive=true;
hive> select * from chartypehive;
OK
ANUBHAV	'ANU'
Time taken: 0.083 seconds, Fetched: 1 row(s)
hive>

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/81/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2213/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/83/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2215/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/86/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2292/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/165/

**Comment by chenliang613** [comment]
LGTM

**Pull request closed without merging**
