### PR TITLE
[CARBONDATA-1739] Clean up store path interface

### PR DESCRIPTION
**Pull request by jackylk**
There are many getStorePath API, this PR unified it in one place: `CarbonProperties.getStorePath`
It can be used in driver side.
Since store path interface is unified, `TableMeta` is not required and it is removed

 - [X] Any interfaces changed?
 Yes
 - [X] Any backward compatibility impacted?
 No
 - [X] Document update required?
No
 - [X] Testing done
No new testcase is added
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
MR2

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1183/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1198/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1199/

**Comment by zzcclp** [comment]
I found the commit 'add s3 in filefactory' appears in many prs.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1201/

**Comment by jackylk** [comment]
@zzcclp because I implement those PR one by one, so it is on top of #1504

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1208/

**Comment by QiangCai** [comment]
LGTM

**Pull request closed without merging**
