### PR TITLE
[TEMP] support prestosql 330 in carbon

### PR DESCRIPTION
**Pull request by ajantha-bhat**
### Why is this PR needed?
 
 
 ### What changes were proposed in this PR?

    
 ### Does this PR introduce any user interface change?
 - No
 - Yes. (please explain the change and update document)

 ### Is any new testcase added?
 - No
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/667/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2373/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/674/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2380/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/696/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2402/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/698/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2404/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2418/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/711/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2424/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/717/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2442/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/733/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2477/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.4/769/

**Comment by ajantha-bhat** [comment]
tested and worked fine. But we will keep 316 support now.

Can use this PR if required later.

**Comment by jxxfxkp** [comment]
Are you sure you can compile successfully? Some packages and classes are not in the right position ...
Even if I change, I still can't start presto-330 because it can't pass guice 

errors:
Explicit bindings are required and io.prestosql.plugin.hive.HdfsConfig is not explicitly bound.
  while locating io.prestosql.plugin.hive.HdfsConfig
    for the 1st parameter of io.prestosql.plugin.hive.HdfsConfigurationInitializer.<init>(HdfsConfigurationInitializer.java:71)
  at org.apache.carbondata.presto.CarbondataModule.configure(CarbondataModule.java:105)
...

**Comment by ajantha-bhat** [comment]
@jxxfxkp : Have you cherry picked this PR? The same errors were resolved in this PR. Open source master cannot work with presto 330. This PR can

**Comment by jxxfxkp** [comment]
I 'm sure to cherry-pick this PR. Some Classes cannot find symbol (OrcFileWriterConfig->OrcWriterConfig,io.prestosql.plugin.hive->io.prestosql.plugin.hive.orc ...) ,Although I can change them, I still get some prestoserver--start errors  (presto330)

**Comment by ajantha-bhat** [comment]
@jxxfxkp : You are right it is not compiling now, It was working. I think presto 330 project has changes its presto-hive dependency after my changes, so it is failing. Let me try to make it work

**Comment by ajantha-bhat** [comment]
@jxxfxkp : can you check this PR. locally UT are passing for presto-330

https://github.com/apache/carbondata/pull/3954

**Pull request closed without merging**
