### PR TITLE
[CARBONDATA-2417] SDK writer goes to infinite wait when consumer thread is dead

### PR DESCRIPTION
**Pull request by ajantha-bhat**
[CARBONDATA-2417]
problem: SDK writer goes to infinite wait when consumer thread is dead

root cause: due to bad record when an exception happens at consumer thread
during write, this message is not reached producer (SDK writer).
So, SDK keeps writing data assuming consumer will consume it. But as a consumer is dead, queue becomes full and queue.put() will be blocked
forever.

Solution: When the consumer is dead, call writer.close() forcefully and
clear queue. so that blocking write will go an and skip writing next
batches. when writer.close() is called by user. Throw an exception that
write is failed
 - [ ] Any interfaces changed? no
 
 - [ ] Any backward compatibility impacted? no
 
 - [ ] Document update required? no

 - [ ] Testing done
      updated the testcase in TestNonTransactionalCarbonTable.scala
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.  NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5528/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4364/

**Comment by ravipesala** [comment]
@ajantha-bhat During any abnormalities it needs to call `CarbonOutputIteratorWrapper.closeWriter` it can close gracefully otherwise unexpected issues like this will come

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4630/

**Comment by ajantha-bhat** [comment]
@ravipesala  : handled as per comments.

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4646/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/5552/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/4389/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4647/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/4648/

**Comment by ravipesala** [comment]
LGTM

**Pull request closed without merging**
