### PR TITLE
[CARBONDATA-2035][DataLoad][Tests] Fix bugs in raising exception through assertion

### PR DESCRIPTION
**Pull request by xuchuanyin**
By default, the "VM parameters" is empty and `-ea` is disabled, so the assert sentence in code will not come into effect, thus causing this problem.
In conclusion, carbondata should not detect&throw exception in this way, we need to correct it.

please refer to this [link](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.10) for more information.

CAUTION
===
**I also noticed that there are many tests that use "assert condition", this may also cause some underlying problems.** 

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 `No`
 - [x] Any backward compatibility impacted?
 `No`
 - [x] Document update required?
`No`
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
`No`
        - How it is tested? Please attach test report.
`Tested in local node`
        - Is it a performance related change? Please attach the performance test report.
`No`
        - Any additional information to help reviewers in testing this change.
 `We should not use assertion to detect/throw exception since assertion is disabled if we don't specify ‘-ea’ VM parameter.`      
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
`Not related`

### CODE REVIEW

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1603/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2838/

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1608/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2843/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1613/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2848/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2927/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2928/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2929/

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2865/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1632/

**Comment by xuchuanyin** [comment]
This issue has been fixed by another PR, so close it here

**Pull request closed without merging**
