### PR TITLE
[CARBONDATA-2265] [DFX]-Load]: Load job fails if 1 folder contains 1000 files

### PR DESCRIPTION
**Pull request by dhatchayani**
Problem : We are keeping the rawTablePages also in memory, but we are no where using it
Solution : Removed storing rawTablePages

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [x] Testing done
        Manual Testing
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/3222/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/4455/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/3973/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
