### PR TITLE
[CARBONDATA-1238] Decouple the datatype convert in core module

### PR DESCRIPTION
**Pull request by chenliang613**
Decouple the datatype convert of Spark in core module：
1.Use decimal(org.apache.spark.sql.types.Decimal.apply()) in spark engine, use java's decimal in other engines.
2.Use org.apache.spark.unsafe.types.UTF8String in spark engine, use String in other engines.
3.Fix Hive integration decimal issues

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2775/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/196/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/705/<h2>Failed Tests: <span class='status-failure'>3</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/705/org.apache.carbondata$carbondata-spark/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/705/org.apache.carbondata$carbondata-spark/testReport/org.apache.carbondata.integration.spark.testsuite.dataload/SparkDatasourceSuite/query_using_SQLContext/'><strong>org.apache.carbondata.integration.spark.testsuite.dataload.SparkDatasourceSuite.query using SQLContext</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/705/org.apache.carbondata$carbondata-spark/testReport/org.apache.carbondata.integration.spark.testsuite.dataload/SparkDatasourceSuite/query_using_SQLContext_without_providing_schema/'><strong>org.apache.carbondata.integration.spark.testsuite.dataload.SparkDatasourceSuite.query using SQLContext without providing schema</strong></a></li></ul><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/705/org.apache.carbondata$carbondata-spark-common-test/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark-common-test</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/705/org.apache.carbondata$carbondata-spark-common-test/testReport/org.apache.carbondata.spark.testsuite.dataretention/DataRetentionConcurrencyTestCase/DataRetention_Concurrency_load_date/'><strong>org.apache.carbondata.spark.testsuite.dataretention.DataRetentionConcurrencyTestCase.DataRetention_Concurrency_load_date</strong></a></li></ul>

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/203/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2782/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/712/<h2>Failed Tests: <span class='status-failure'>4</span></h2><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-core/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-core</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.writer/CarbonFooterWriterTest/testWriteFactMetadata/'><strong>org.apache.carbondata.core.writer.CarbonFooterWriterTest.testWriteFactMetadata</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-core/testReport/org.apache.carbondata.core.writer/CarbonFooterWriterTest/testReadFactMetadata/'><strong>org.apache.carbondata.core.writer.CarbonFooterWriterTest.testReadFactMetadata</strong></a></li></ul><h3><a name='carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark' /><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-spark/testReport'>carbondata-pr-spark-1.6/org.apache.carbondata:carbondata-spark</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-spark/testReport/org.apache.carbondata.integration.spark.testsuite.dataload/SparkDatasourceSuite/query_using_SQLContext/'><strong>org.apache.carbondata.integration.spark.testsuite.dataload.SparkDatasourceSuite.query using SQLContext</strong></a></li><li><a href='https://builds.apache.org/job/carbondata-pr-spark-1.6/712/org.apache.carbondata$carbondata-spark/testReport/org.apache.carbondata.integration.spark.testsuite.dataload/SparkDatasourceSuite/query_using_SQLContext_without_providing_schema/'><strong>org.apache.carbondata.integration.spark.testsuite.dataload.SparkDatasourceSuite.query using SQLContext without providing schema</strong></a></li></ul>

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/225/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2805/

**Comment by chenliang613** [comment]
raise a new PR #1197 , close the old one.

**Pull request closed without merging**
