### PR TITLE
[CARBONDATA-3509] Support disable query prefetch by configuration

### PR DESCRIPTION
**Pull request by ajantha-bhat**
**Support disable query prefetch by configuration**:
Prefetch runs in asynch thread in query and it is always enable in query flow. If some user wants to disable it, they can use this property to disable and observe in logs.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed? NA
 
 - [ ] Any backward compatibility impacted? NA
 
 - [ ] Document update required? updated

 - [ ] Testing done. done

 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/383/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/384/

**Comment by zzcclp** [comment]
@ajantha-bhat this pr is a new feature for adding a new parameter , better create a jira task to trace it.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/384/

**Comment by ajantha-bhat** [comment]
@zzcclp : Added JIRA

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/384/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.1/385/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.2/385/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/385/

**Comment by kunal642** [comment]
LGTM

**Comment by zzcclp** [comment]
LGTM

**Pull request closed without merging**
