### PR TITLE
[CARBONDATA-3383] fix thrift version conflict bug in examples module

### PR DESCRIPTION
**Pull request by lamber-ken**
Thrift version conflict in examples module, in example module needs carbondata-hive and carbondata-store-sdk, one version is 0.9.3 another is 0.9.2. This cause NPE when use carbondata-sdk write demo data.

[JIRA-3383](https://issues.apache.org/jira/browse/CARBONDATA-3383)

### Detail stackstrace
```
java.lang.NullPointerException
    at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:356)
    at org.apache.carbondata.format.FileFooter3$FileFooter3StandardScheme.write(FileFooter3.java:1053)
    at org.apache.carbondata.format.FileFooter3$FileFooter3StandardScheme.write(FileFooter3.java:877)
    at org.apache.carbondata.format.FileFooter3.write(FileFooter3.java:768)
    at org.apache.carbondata.core.util.CarbonUtil.getByteArray(CarbonUtil.java:1444)
    at org.apache.carbondata.processing.store.writer.v3.CarbonFactDataWriterImplV3.writeFooterToFile(CarbonFactDataWriterImplV3.java:122)
    at org.apache.carbondata.processing.store.writer.v3.CarbonFactDataWriterImplV3.writeFooter(CarbonFactDataWriterImplV3.java:415)
    at org.apache.carbondata.processing.store.CarbonFactDataHandlerColumnar.closeHandler(CarbonFactDataHandlerColumnar.java:502)
    at org.apache.carbondata.processing.loading.steps.CarbonRowDataWriterProcessorStepImpl.processingComplete(CarbonRowDataWriterProcessorStepImpl.java:234)
    at org.apache.carbondata.processing.loading.steps.CarbonRowDataWriterProcessorStepImpl.finish(CarbonRowDataWriterProcessorStepImpl.java:212)
    at org.apache.carbondata.processing.loading.steps.CarbonRowDataWriterProcessorStepImpl.doExecute(CarbonRowDataWriterProcessorStepImpl.java:179)
    at org.apache.carbondata.processing.loading.steps.CarbonRowDataWriterProcessorStepImpl.execute(CarbonRowDataWriterProcessorStepImpl.java:133)
    at org.apache.carbondata.processing.loading.DataLoadExecutor.execute(DataLoadExecutor.java:52)
    at org.apache.carbondata.hadoop.api.CarbonTableOutputFormat$1.run(CarbonTableOutputFormat.java:274)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x] Any interfaces changed?
 
 - [x] Any backward compatibility impacted?
 
 - [x] Document update required?

 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11453/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3187/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3384/

**Comment by zzcclp** [comment]
retest this please.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11460/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3194/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3391/

**Comment by lamber-ken** [comment]
I think the maven dependencies of CarbonData project need to reorganize, some place use version directly, some place miss version. It may cause version conflict, not only thrift version. So it's need to open a new big issue to resolve this problem, this pr can't resolve it, so close this.

for example, `processing/pom.xml`
```
<dependency>
  <groupId>org.apache.carbondata</groupId>
  <artifactId>carbondata-core</artifactId>
  <version>${project.version}</version>
</dependency>
<dependency>
  <groupId>com.univocity</groupId>
  <artifactId>univocity-parsers</artifactId>
  <version>2.2.1</version>
</dependency>
```
`datamap/mv/plan/pom.xml`
```
<plugin>
  <groupId>com.ning.maven.plugins</groupId>
  <artifactId>maven-duplicate-finder-plugin</artifactId>
  <configuration>
    <skip>true</skip>
  </configuration>
</plugin>
```

**Pull request closed without merging**
