### PR TITLE
Support using Apache CarbonData in notebook

### PR DESCRIPTION
**Pull request by xubo245**
### Why is this PR needed?
 Support using Apache CarbonData in notebook
 
 ### What changes were proposed in this PR?
Support using Apache CarbonData in notebook
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No,only add doc

### CODE REVIEW

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://159.138.8.58:12602/job/ApacheCarbonPRBuilder2.3/6385/

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_2.4.5/4677/

**Comment by chenliang613** [comment]
+1, good contribution, as of now many users are using notebook to do data analysis.

**Comment by shenjiayu17** [comment]
Build Failed  with Spark 3.1, Please check CI http://159.138.8.58:12602/job/ApacheCarbon_PR_Builder_3.1/769/

**Pull request merged**
