### PR TITLE
[CARBONDATA-1942] Documentation for Concurrent Lock Retries

### PR DESCRIPTION
**Pull request by AyushCarb1**
Add documentation for concurrent lock retires. Add the parameter name, Default value, and description

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2359/

**Pull request closed without merging**
