### PR TITLE
[CARBONDATA-1069] Fixed Compaction Failure issue on Cluster

### PR DESCRIPTION
**Pull request by PallaviSingh1992**

### CODE REVIEW

**Comment by kumarvishal09** [comment]
Please rebase your PR.

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2138/

**Comment by PallaviSingh1992** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2234/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/107/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/300/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2422/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2423/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/302/

**Comment by gvramana** [comment]
Is this issue still valid? Please explain what is the problem root cause? What is fix about?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by PallaviSingh1992** [comment]
This issue has been fixed by manish's PR

**Pull request closed without merging**
