### PR TITLE
[HOTFIX] Correct the sentence to be meaningful

### PR DESCRIPTION
**Pull request by brijoobopanna**
Modify the wording to make it meaningful with the context

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [x ] Any interfaces changed?
 No
 - [x] Any backward compatibility impacted?
No 
 - [x] Document update required?
No

### CODE REVIEW

**Comment by sraghunandan** [comment]
LGTM

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/6268/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/6639/

**Comment by chenliang613** [comment]
add to whitelist

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/7921/

**Pull request closed without merging**
