### PR TITLE
[CARBONDATA-2626] Fix bugs in sequence of column page

### PR DESCRIPTION
**Pull request by xuchuanyin**
In tableSpec, the sort column dimensions are in the left of those
dictionary dimensions.

Create table and load data to it. The table schema is:

```
sql(
 s"""
 | CREATE TABLE $bloomDMSampleTable(id INT, name STRING, city STRING, age INT,
 | s1 STRING, s2 STRING, s3 STRING, s4 STRING, s5 STRING, s6 STRING, s7 STRING, s8 STRING)
 | STORED BY 'carbondata' TBLPROPERTIES('table_blocksize'='128', 'dictionary_include'='id', 'sort_columns'='name')
 | """.stripMargin)
```

 In tablespec, the first dimension spec is 'name' which is sort_columns but not dictionary. But Carbondata now treat it as dictionary page. (See TablePage Line94)
 
Tested before and after this implementation on the following scenarios, the dataload and query is fine:

1. Create & load data with master code, query with this bug-fix code
2. Create & load data with this bug-fix code, query with master code

each scenario with test cases:

1. dictionary: id, sort_columns: name
2. dictionary: id, sort_columns: id
3. dictionary: id, sort_columns: id,name
4. dictionary: id, sort_columns: name,id

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by xuchuanyin** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6459/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/5384/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/6461/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/5292/

**Comment by jackylk** [comment]
Have you tested using data generated by 1.4.0 and read by this PR, to ensure the backward compatibility?

**Comment by xuchuanyin** [comment]
I've tested it, it's OK. please refer to the description of this PR

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
