### PR TITLE
[CARBONDATA-1236] Support absolute path without scheme in loading - h…

### PR DESCRIPTION
**Pull request by dhatchayani**
we should not check for the file type after adding a / in front. this PR will change the logic to first check the file type and then append a / if needed

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/184/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/2763/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/carbondata-pr-spark-1.6/693/

**Comment by gvramana** [comment]
LGTM

**Pull request merged**
