### PR TITLE
[HOTFIX] Intializing the CSDK object reference to NULL

### PR DESCRIPTION
**Pull request by brijoobopanna**
Changes in this PR:

NULL intialization done to JObjects in CPP files of CSDK. This prevents seg fault when these objects are referenced without initilization .

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [NA] Any interfaces changed?
 
 - [NA] Any backward compatibility impacted?
 
 - [NA] Document update required?

 - [OK] Testing done using existing test cases
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ NA] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1466/

**Comment by BJangir** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9724/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1676/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/1471/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/1681/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/9729/

**Comment by kunal642** [comment]
LGTM

**Pull request closed without merging**
