### PR TITLE
[CARBONDATA-3435] Show-Metacache behaviour change

### PR DESCRIPTION
**Pull request by NamanRastogi**
**Dependency: [PR 3245](https://github.com/apache/carbondata/pull/3245)**

Behaviour of `SHOW METACACHE ON TABLE tblName` is not same for Driver and Index-Server. Need same behavior for both.

Old behaviour: Show all the entries for all the child tables, even if the size is zero.
New behaviour: Don't show any entry with size 0 in both Driver and Index-Server.

 - [x] Any interfaces changed?  ->  No
 - [x] Any backward compatibility impacted?  ->  No
 - [x] Document update required?  ->  No
 - [x] Testing done?  ->  Yes
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3555/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11829/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3761/

**Comment by ravipesala** [comment]
@NamanRastogi I am not what behaviour is different? Better provide some example. And also the PR 3259 and this will be having conflicts I guess.

**Comment by NamanRastogi** [comment]
@ravipesala Earlier we were displaying child tables in `show metacache on table` command even if the child table is not in cache. Not we are removing all the "zero" entries.

**Comment by ravipesala** [comment]
Ok, Please add same in PR description.

**Comment by ravipesala** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/3695/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11970/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3906/

**Pull request closed without merging**
