### PR TITLE
[HOTFIX] Removed scala dependency from carbon core module

### PR DESCRIPTION
**Pull request by ravipesala**
Removed scala dependencies from carbon-core and sdk modules.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/229/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.1, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.3/8468/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/398/

**Comment by jackylk** [comment]
spark 2.3 has random failure? @ravipesala @QiangCai

**Comment by xuchuanyin** [comment]
@jackylk I got preaggregate related failure in spark2.3 

http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.3/8479/

it seems all the failed testcase all contains sql("reset")

**Comment by jackylk** [comment]
LGTM

**Pull request closed without merging**
