### PR TITLE
[CARBONDATA-1668] Remove isTableSplitPartition in data loading

### PR DESCRIPTION
**Pull request by jackylk**
This option is always false, related code can be removed

 - [X] Any interfaces changed?
 No

 - [X] Any backward compatibility impacted?
 No

 - [X] Document update required?
No

 - [X] Testing done
No new testcase is required

 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/810/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1443/

**Comment by QiangCai** [comment]
LGTM

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/831/

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1464/

**Comment by QiangCai** [comment]
test this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/838/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1471/

**Pull request closed without merging**
