### PR TITLE
fix bug in Spi2CarbondataTypeMapper method, it will cause exception like

### PR DESCRIPTION
**Pull request by linqer**
com.facebook.presto.spi.PrestoException: DECIMAL precision must be in range [1, 38]
         at com.facebook.presto.spi.type.DecimalType.validatePrecisionScale(DecimalType.java:94)
         at com.facebook.presto.spi.type.ShortDecimalType.<init>(ShortDecimalType.java:34)
         at com.facebook.presto.spi.type.DecimalType.createDecimalType(DecimalType.java:37)
         at org.apache.carbondata.presto.CarbondataRecordSetProvider.Spi2CarbondataTypeMapper(CarbondataRecordSetProvider.java:257)

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[CARBONDATA-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
 - [ ] Testing done
 
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - What manual testing you have done?
        - Any additional information to help reviewers in testing this change.
         
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
                 
---

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by ravipesala** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3378/

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/781/

**Comment by ravipesala** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/108/

**Comment by linqer** [comment]
Please note that: In addition to solving the bug " DECIMAL precision must be in range ", another modification has been made, there is one bit incompatible: 

1. When converting carbondata type to presto type,  if the type is uncertain, original code will convert it to the Presto String type. Now an Unsupport exception will be throw out, 
( CarbondataMetadata.CarbondataType2SpiMapper is changed to  CarbondataType.getSpiType）

2. When converting presto type to carbondata type,  if the type is uncertain, original code will convert it to the Carbon String type. Now an Unsupport exception will be throw out,
（CarbondataRecordSetProvider.Spi2CarbondataTypeMapper  is changed to CarbondataType.toCarbonType）

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/810/

**Comment by ravipesala** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/136/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3409/

**Comment by linqer** [comment]
now I should close this pull requests? and will some one merge the code change to master branch ?

**Comment by anubhav100** [comment]
@linqer how to test this pr can you provide reproducable steps?

**Comment by anubhav100** [comment]
@linqer please correct your PR title as per : https://github.com/apache/carbondata/blob/master/docs/How-to-contribute-to-Apache-CarbonData.md

**Comment by linqer** [comment]
Table Script：
carbon.sql("create table nation ( n_nationkey int, n_name string, n_regionkey int, n_comment string ) stored by 'carbondata'")

The lastest master branch:
sql: select * from nation where n_name='ALGERIA';

2017-08-17T14:17:07.675+0800	DEBUG	query-execution-9	com.facebook.presto.execution.QueryStateMachine	Query 20170817_061707_00025_mpcq7 is FAILED
2017-08-17T14:17:07.675+0800	ERROR	query-execution-7	com.facebook.presto.execution.QueryStateMachine	Query 20170817_061707_00025_mpcq7 failed
com.facebook.presto.spi.PrestoException: DECIMAL precision must be in range [1, 38]
	at com.facebook.presto.spi.type.DecimalType.validatePrecisionScale(DecimalType.java:94)
	at com.facebook.presto.spi.type.ShortDecimalType.<init>(ShortDecimalType.java:34)
	at com.facebook.presto.spi.type.DecimalType.createDecimalType(DecimalType.java:37)
	at org.apache.carbondata.presto.CarbondataRecordSetProvider.Spi2CarbondataTypeMapper(CarbondataRecordSetProvider.java:259)
	at org.apache.carbondata.presto.CarbondataRecordSetProvider.fillFilter2QueryModel(CarbondataRecordSetProvider.java:134)
	at org.apache.carbondata.presto.CarbondataRecordSetProvider.getRecordSet(CarbondataRecordSetProvider.java:110)
	at org.apache.carbondata.presto.CarbondataPageSourceProvider.createPageSource(CarbondataPageSourceProvider.java:48)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:213)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
	
The pr-1234 branch:

git fetch origin pull/1234/head:pr-1234

sql: select * from nation where n_name='ALGERIA';

select * from nation where n_name='ALGERIA';
 n_nationkey | n_name  | n_regionkey |                      n_comment                      
-------------+---------+-------------+-----------------------------------------------------
           0 | ALGERIA |           0 |  haggle. carefully final deposits detect slyly agai

**Comment by linqer** [comment]
[CARBONDATA-issue number>] Title of the pull request
there is not a existing CARBONDATA-issue number of this bug.

**Comment by anubhav100** [comment]
@linqer please create a jira

**Comment by anubhav100** [comment]
@linqer i am unable to reproduce this bug on latest master branch can you provide more details

**Comment by linqer** [comment]
chould you give your skype ? i can show you it.

**Comment by anubhav100** [comment]
@linquer can you give me your CSV using the steps you give to me I can not replicate the bug and you can show it to me on wechat

**Comment by linqer** [comment]
[nationdata.zip](https://github.com/apache/carbondata/files/1233173/nationdata.zip)
this is data file

**Comment by linqer** [comment]
# 1. The latest master code have this issue:

latestcode

`create statement: carbon.sql("create table nation ( n_nationkey int, n_name string, n_regionkey int, n_comment string ) stored by 'carbondata'")`

`load statement: carbon.sql("LOAD DATA INPATH '/viphome/qr/testdata/nation_null.csv' INTO TABLE nation  OPTIONS('DELIMITER'='\u0001')")`

**//Note: "select * from nation " is ok;  but " select * from nation where n_name='INDIA' throws exception**
`sql: select * from nation where n_name='INDIA'; `

image
image

# 2. pr-1234 can fix this issue
`git fetch origin pull/1234/head:pr-1234`

`sql: select * from nation where n_name='INDIA`
image

**Comment by anubhav100** [comment]
@linqer please give me nation_null.CSV as well I will try to replicate it again today

**Comment by linqer** [comment]
yes, I have upload it . could you see my comment above?
"nationdata.zip
this is data file"

**Comment by anubhav100** [comment]
@linqer ya i will review it

**Comment by anubhav100** [comment]
@linqer

in carbon
 
 create table nation5 ( n_nationkey int, n_name string, n_regionkey int, n_comment string ) stored by 'carbondata';

LOAD DATA INPATH '/nation.csv' INTO TABLE nation5 OPTIONS('DELIMITER'='|' , 'QUOTECHAR'='\"','FILEHEADER'='N_NATIONKEY,N_NAME,N_REGIONKEY,N_COMMENT');

0: jdbc:hive2://localhost:10000> select * from nation5 where n_name='INDIA';
+--------------+---------+--------------+--------------------------------------------------------------------+--+
| n_nationkey  | n_name  | n_regionkey  |                             n_comment                              |
+--------------+---------+--------------+--------------------------------------------------------------------+--+
| 8            | INDIA   | 2            | ss excuses cajole slyly across the packages. deposits print aroun  |
+--------------+---------+--------------+--------------------------------------------------------------------+--+

in presto

presto:default> select * from nation5 where n_name='INDIA';
 n_nationkey | n_name | n_regionkey |                             n_comment                             
-------------+--------+-------------+-------------------------------------------------------------------
           8 | INDIA  |           2 | ss excuses cajole slyly across the packages. deposits print aroun 
(1 row)

Query 20170818_092022_00001_7u72x, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:16 [1 rows, 4B] [0 rows/s, 0B/s]

**Comment by anubhav100** [comment]
@linqer plus in your script for load command 

0: jdbc:hive2://localhost:10000> LOAD DATA INPATH '/nation_null.csv' INTO TABLE nation4 OPTIONS('DELIMITER'='\u0001');
Error: scala.StringContext$InvalidEscapeException: invalid escape '\u' not one of [\b, \t, \n, \f, \r, \\, \", \'] at index 0 in "\u0001". Use \\ for literal \. (state=,code=0)

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/247/

**Comment by chenliang613** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/279/

**Comment by anubhav100** [comment]
@linqer as you suggested i tried it on 3 node presto cluster but bug is not getting replicated

in presto

select * from nation where n_name='INDIA';
n_nationkey | n_name | n_regionkey |                             n_comment                            
-------------+--------+-------------+-------------------------------------------------------------------
          8 | INDIA  |           2 | ss excuses cajole slyly across the packages. deposits print aroun
(1 row)

this is my cordinator config.properties file

coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8086
query.initial-hash-partitions=3
query.max-memory=10GB
query.max-memory-per-node=5GB
discovery-server.enabled=true
task.concurrency=4
discovery.uri=

**Comment by linqer** [comment]
yes, it can works fine with presto 0.164+, can't not work with 0.164-;

**Pull request closed without merging**
