### PR TITLE
[CARBONDATA-1221] Documentation - removed the unused parameter from c…

### PR DESCRIPTION
**Pull request by Ayushi93**
…onfig reference

The following parameters are removed from the code, hence updated the document for the same.

carbon.inmemory.record.size
no.of.cores.to.load.blocks.in.driver

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by sgururajshetty** [comment]
LGTM
@chenliang613 kindly review and merge

**Comment by chenliang613** [comment]
LGTM

**Comment by chenliang613** [comment]
@Ayushi93  please config your email info in your local git environment.

**Comment by Ayushi93** [comment]
@chenliang It is already configured. ☺️

**Comment by chenliang613** [comment]
No, after config email, you need to push your commit again.

This PR's commit record still be wrong, as below : 
commit 97685add85d5304a485e2632110403aeef6f27f3
Author: Ayushi93 <31242854+Ayushi93@users.noreply.github.com>
Date:   Tue Aug 22 16:53:47 2017 +0530

    [CARBONDATA-1221] Documentation - removed the unused parameter from config reference

    The following parameters are removed from the code, hence updated the document for the same.

    carbon.inmemory.record.size
    no.of.cores.to.load.blocks.in.driver

**Comment by chenliang613** [comment]
retest this please

**Comment by ravipesala** [comment]
SDV Build Fail , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/707/

**Comment by chenliang613** [comment]
retest this please

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Can one of the admins verify this patch?

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/20/

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
