### PR TITLE
[HOTFIX]: Added Prepriming SDV test cases

### PR DESCRIPTION
**Pull request by vikramahuja1001**
### Why is this PR needed?
 SDV test cases for Index Server Prepriming
 
 ### What changes were proposed in this PR?
Added Prepriming SDV test cases
    
 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - Yes

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/2751/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/1038/

**Comment by jackylk** [comment]
I think SDV suite is currently not running, is it better to add in CI suite? @akashrn5 please check

**Comment by akashrn5** [comment]
@jackylk in the existing UT CI, we cannot enable index server and test for pre-priming, that is the reason he has added here.
@vikramahuja1001 please share the screenshot of the SDV buid with this test cases and once pass, we can review and optimize further.

**Pull request closed without merging**
