### PR TITLE
[HOTFIX] Fix random 11 testcase failure in CI

### PR DESCRIPTION
**Pull request by ajantha-bhat**
### Why is this PR needed?
 There is a random 11 testcase failure in CI.
Screenshot from 2020-10-12 14-34-23
 
 ### What changes were proposed in this PR?
a) After analyzing and adding logs, found out that test case added in #3608 has not reset the `carbon.enable.auto.load.merge` carbon property.
This issue is random as if any other testcase  (which resets that carbon property) in `CarbonIndexFileMergeTestCase`   is ran before issue testcase, it will set the value to false and mask the issue.  Also in a suite, order of testcase execution is not same always. So, it is random.
 
b) Test case added by  #3832 has a problem. `test cdc with compaction` fails randomly because 12.2 segment will not be there and merge carbon property is not reset when this is failed.
It is because auto compaction sometimes 0.1 goes for marked for delete during merge operation. There is no  record mismatch. Just that 12.2 doesn't exist. It will be in some other segment name. currently removed checking that 12.2 segment.

 ### Does this PR introduce any user interface change?
 - No

 ### Is any new testcase added?
 - No

### CODE REVIEW

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4173/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2430/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4191/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2448/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4362/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2612/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2618/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4368/

**Comment by ajantha-bhat** [comment]
@Karan980, @akashrn5 , @QiangCai : Please check and merge this once new build passes.

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2629/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4380/

**Comment by akashrn5** [comment]
@ajantha-bhat failed again i think, please check if the same cause or something else

**Comment by ajantha-bhat** [comment]
@akashrn5 : logs were removed as one issue was found. definitely some other issue also there. Added logs and pushed again.

**Comment by akashrn5** [comment]
> @akashrn5 : logs were removed as one issue was found. definitely some other issue also there. Added logs and pushed again.

yeah

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4386/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2634/

**Comment by ajantha-bhat** [comment]
@akashrn5 : Now it was failed because `test cdc with compaction` has failed. So, reset didn't happen.

"opTime":"87 ms","table":"default.target","extraInfo":{"force":"false","internal":"false"}}
^[[31m- test cdc with compaction *** FAILED ***^[[0m
^[[31m  0 did not equal 1 (MergeTestCase.scala:1047)^[[0m

**Comment by ajantha-bhat** [comment]
@akashrn5 : I will anyhow reset this property in before all of `CarbonIndexFileMergeTestCase`. so it won't leads to this 11 testcase failures.

**Comment by ajantha-bhat** [comment]
@Zhangshunyu 

Screenshot from 2020-10-13 18-47-37

When you run this test case multiple times, it fails locally also. segment 12.X doesn't exist sometimes.

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4414/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2660/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4420/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2666/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4425/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2671/

**Comment by ajantha-bhat** [comment]
@akashrn5 , @QiangCai : PR is ready. There are some more random failures are there in CI. someone can analyze and handle in other PRs I guess.

**Comment by ajantha-bhat** [comment]
retest this plese

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2701/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4455/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2725/

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4479/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4491/

**Comment by ajantha-bhat** [comment]
retest this please

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12545/job/ApacheCarbonPRBuilder2.3/4492/

**Comment by CarbonDataQA1** [comment]
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12545/job/ApacheCarbon_PR_Builder_2.4.5/2738/

**Comment by QiangCai** [comment]
LGTM,  we will raise more PRs to fix other random failures in CI

**Pull request closed without merging**
