### PR TITLE
[HOTFIX] [CARBONDATA-2027] Fix the Failing Concurrent Test cases for Ci

### PR DESCRIPTION
**Pull request by anubhav100**
Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2784/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1551/

**Comment by anubhav100** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2788/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.1, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/1557/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2792/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2888/

**Comment by anubhav100** [comment]
@jackylk  please review i have corrected the data rentention test cases and club the TestInsertUpdateConcurrentTest and TestInsertOverwriteAndCompaction test case but even after taking the future out  in all test cases,test cases of TestInsertUpdateConcurrentTest is failing randomly only in ci not on local may be because any one of the two threads one which is running update and other one which is executing insert overwrite get executed first which is not correct scenario insert overwrite must get executed first. please suggest?

**Comment by jackylk** [comment]
I agree with you. With taking the future, the chance is lower, but still there. Let me merge this PR first, if random failure still exist, we need to find a way to control the order of command execution

**Pull request closed without merging**
