### PR TITLE
fixed bug for IsNull and IsNotNull clause in presto

### PR DESCRIPTION
**Pull request by steven-qin**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[CARBONDATA-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).
 - [ ] Testing done
 
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - What manual testing you have done?
        - Any additional information to help reviewers in testing this change.
         
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
                 
---

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
add to whitelist

**Comment by ravipesala** [comment]
Build Success with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/779/

**Comment by ravipesala** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3377/

**Comment by ravipesala** [comment]
SDV Build Success with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/107/

**Comment by ravipesala** [comment]
SDV Build Failed with Spark 2.1, Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/135/

**Comment by ravipesala** [comment]
Build Failed with Spark 1.6, Please check CI http://144.76.159.231:8080/job/ApacheCarbonPRBuilder/809/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder/3408/

**Comment by anubhav100** [comment]
@steven-qin can you please provide reproducable steps?

**Comment by anubhav100** [comment]
@steven-qin 
1.please correct your PR title as per : https://github.com/apache/carbondata/blob/master/docs/How-to-contribute-to-Apache-CarbonData.md
2.Can you please provide the reproduce steps for this issue.

**Comment by steven-qin** [comment]
@anubhav100 
select * from nation where n_comment is null;
select * from nation where n_comment is not null;
You have fixed the problem of pr-1235.

**Comment by anubhav100** [comment]
@steven-qin this issue does not exist

**Comment by steven-qin** [comment]
Hi @anubhav100 
Based on the commit "69c634c5f32dfc333919d0b3e6cc342e15638cf7",I find the problem and subsequent versions have been fixed it.

git checkout -b  pre  69c634c5f32dfc333919d0b3e6cc342e15638cf7

mvn -DskipTests -Pspark-2.1 -Dspark.version=2.1.0 clean package

create statemant: carbon.sql("create table nation ( n_nationkey int, n_name string, n_regionkey int, n_comment string ) stored by 'carbondata'")

load statemant: carbon.sql("LOAD DATA INPATH '/viphome/qr/testdata/nation_null.csv' INTO TABLE nation  OPTIONS('DELIMITER'='\u0001')")

sql: select * from nation where n_comment is null;
     select * from nation where n_comment is not null;
not_null_clause


null_clause

**Pull request closed without merging**
