### PR TITLE
[CARBONDATA-1872][API] Clean up unused constant in CarbonCommonConstant

### PR DESCRIPTION
**Pull request by jackylk**
Remove unused constant string in CarbonCommonConstant

 - [X] Any interfaces changed?
 NO
 - [X] Any backward compatibility impacted?
 NO
 - [X] Document update required?
No
 - [X] Testing done
No logic is modified, it can be tested by existing testsuite
 
 - [X] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA. 
NA

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/574/

**Comment by QiangCai** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1856/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/628/

**Comment by ravipesala** [comment]
retest this please

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/2113/

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.2.0, Please check CI http://88.99.58.216:8080/job/ApacheCarbonPRBuilder/888/

**Comment by ravipesala** [comment]
LGTM

**Comment by ravipesala** [comment]
@jackylk I have reverted this commit as SDV tests are compilation failed because of some constants removed. Please fix it. I merge again.

**Pull request closed without merging**
