### PR TITLE
[CARBONDATA-1814] Fix alter stream table property issue

### PR DESCRIPTION
**Pull request by QiangCai**
Fix alter stream table property issue

 - [x] Any interfaces changed?
 no
 - [x] Any backward compatibility impacted?
 no
 - [x] Document update required?
  no
 - [x] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
         yes, added
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by geetikagupta16** [comment]
@QiangCai The PR for this issue has been raised #1590

**Comment by QiangCai** [comment]
@geetikagupta16 
ok, I will close this PR.
can you move test case to pr1590

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1575/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/1976/

**Comment by geetikagupta16** [comment]
Thanks @QiangCai 
Sure will move the test case

**Pull request closed without merging**
