### PR TITLE
[WIP] delete issue test case

### PR DESCRIPTION
**Pull request by QiangCai**
```
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+
|smallintfield|intfield|bigintfield|floatfield|doublefield|decimalfield|timestampfield     |datefield |stringfield|varcharfield|charfield|
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|2            |2       |2          |2.1       |2.1        |2.1234      |2017-06-12 23:59:02|2017-06-12|abc2       |abcd2       |abcde2   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |3.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+

```

after delete from $tableName where smallIntField = 2
the decimalfield is incorrect
```
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+
|smallintfield|intfield|bigintfield|floatfield|doublefield|decimalfield|timestampfield     |datefield |stringfield|varcharfield|charfield|
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|-1           |-1      |-1         |-1.1      |-1.1       |-1.1234     |2017-06-11 00:00:01|2017-06-11|abc1       |abcd1       |abcde1   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
|3            |3       |3          |3.1       |3.1        |2.1234      |2017-06-13 23:59:03|2017-06-13|abc3       |abcd3       |abcde3   |
+-------------+--------+-----------+----------+-----------+------------+-------------------+----------+-----------+------------+---------+

```

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder2.1/2915/

**Comment by CarbonDataQA** [comment]
Build Failed  with Spark 2.3.2, Please check CI http://136.243.101.176:8080/job/carbondataprbuilder2.3/11176/

**Comment by CarbonDataQA** [comment]
Build Failed with Spark 2.2.1, Please check CI http://95.216.28.178:8080/job/ApacheCarbonPRBuilder1/3146/

**Comment by akashrn5** [comment]
@QiangCai , i have fixed and raised PR #3189 , please review and you can close this PR

**Pull request closed without merging**
