### PR TITLE
[CARBONDATA-1842]Fix 'wrong argument number' error of class Cast for Spark 2.2 when pattern matching

### PR DESCRIPTION
**Pull request by zzcclp**
In class 'org.apache.spark.sql.hive.CarbonPreAggregateQueryRules', there is an 'wrong argument number' error of class 'org.apache.spark.sql.catalyst.expressions.Cast' when compile with Spark 2.2, because the constructor of class org.apache.spark.sql.catalyst.expressions.Cast has two arguments in Spark 2.1, but it needs three arguments in Spark 2.2.

Be sure to do all of the following checklist to help us incorporate 
your contribution quickly and easily:

 - [ ] Any interfaces changed?
 
 - [ ] Any backward compatibility impacted?
 
 - [ ] Document update required?

 - [ ] Testing done
        Please provide details on 
        - Whether new unit test cases have been added or why no new tests are required?
        - How it is tested? Please attach test report.
        - Is it a performance related change? Please attach the performance test report.
        - Any additional information to help reviewers in testing this change.
       
 - [ ] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.

### CODE REVIEW

**Comment by zzcclp** [comment]
After  merging PR #1542 , there is 'wrong argument number' error in CarbonPreAggregateQueryRules when profile of spark-2.2 is active .
@kunal642 , @jackylk , @sounakr , please check this. thanks.

**Comment by CarbonDataQA** [comment]
Build Success with Spark 2.1.0, Please check CI http://136.243.101.176:8080/job/ApacheCarbonPRBuilder1/1624/

**Comment by ravipesala** [comment]
SDV Build Success , Please check CI http://144.76.159.231:8080/job/ApacheSDVTests/2015/

**Comment by zzcclp** [comment]
I have tested successfully with below commands:
1. mvn -DskipTests -Pspark-2.2 -Phadoop-2.2.0 -Pbuild-with-format -Dspark.version=2.2.0 -Dhadoop.version=2.6.0-cdh5.7.1 clean package
2. mvn -Pspark-2.1 -Phadoop-2.2.0 -Pbuild-with-format -Dspark.version=2.1.2 -Dhadoop.version=2.6.0-cdh5.7.1 clean package

**Comment by kunal642** [comment]
@zzcclp I have already handled this in #1508. 
a new Expression is already defined by @sounakr which will take care of the Cast compatibility between spark-2.1 and spark-2.2

**Comment by zzcclp** [comment]
ok, i close this pr

**Comment by zzcclp** [comment]
resolved by #1508

**Pull request closed without merging**
